'use client'

import { useState, useEffect } from 'react'
import { useRouter, useParams } from 'next/navigation'
import Nav from '../../../../../../components/Nav'
import { supabase } from '../../../../../../../lib/supabase'
import { useEntitlement } from '../../../../../../../lib/useEntitlement'
import PaywallCard from '../../../../../../components/PaywallCard'
import { TEMPLATES } from '../../../../../../../lib/supply-chain/templates'

const POSITIVE_RESPONSES = ['yes', 'yes —', 'no incidents', 'fully', 'always', 'gold', 'silver', 'bronze']
const NEGATIVE_RESPONSES = ['no', 'none', 'unknown', 'yes — unresolved', 'yes — ongoing', 'not applicable']

// Prefix-matches the stored answer against NEGATIVE_RESPONSES / POSITIVE_RESPONSES.
//
// ⚠️ Multi-value answers are comma-joined strings ("CDP, GRI"). This function is
// order-sensitive: it reads only the start of the string. That is currently safe
// ONLY because env_reporting's 'None' option is mutually exclusive in the portal
// (app/supplier/[token]/page.tsx), so 'None' can never appear after another value.
//
// If 'None' is ever made non-exclusive, or another question becomes type:'checkbox'
// with an option starting 'no'/'none', this chip will report a colour that depends
// on join order. Fix by matching against the split parts, not the raw string.
const getResponseColor = (response: string): string => {
  const lower = response.toLowerCase()
  if (POSITIVE_RESPONSES.some(p => lower.startsWith(p))) return '#0F6E56'
  if (NEGATIVE_RESPONSES.some(n => lower === n || lower.startsWith(n))) return '#B91C1C'
  return 'var(--color-module-climate)'
}

const GRAD = 'var(--color-brand)'

export default function SupplierResponseViewer() {
  const isPaid = useEntitlement('supply-chain')
  const router = useRouter()
  const params = useParams()
  const campaignId = params.id as string
  const supplierId = params.supplierId as string

  const [supplier, setSupplier] = useState<any>(null)
  const [campaign, setCampaign] = useState<any>(null)
  const [sections, setSections] = useState(TEMPLATES.ecovadis.sections)
  const [responses, setResponses] = useState<Record<string, string>>({})
  const [loading, setLoading] = useState(true)
  const [activeSection, setActiveSection] = useState(0)

  useEffect(() => {
    loadData()
  }, [supplierId])

  const loadData = async () => {
    setLoading(true)
    const { data: sup } = await supabase
      .from('campaign_suppliers')
      .select('*, supplier_campaigns(*)')
      .eq('id', supplierId)
      .single()

    const { data: resps } = await supabase
      .from('supplier_responses')
      .select('*')
      .eq('campaign_supplier_id', supplierId)

    if (sup) {
      setSupplier(sup)
      const camp = sup.supplier_campaigns
      setCampaign(camp)
      const template = camp?.questionnaire_template || 'ecovadis'
      setSections((TEMPLATES[template] || TEMPLATES.ecovadis).sections)
    }
    if (resps) {
      const map: Record<string, string> = {}
      resps.forEach((r: any) => { map[r.question_id] = r.response })
      setResponses(map)
    }
    setLoading(false)
  }

  const totalQuestions = sections.reduce((s, sec) => s + sec.questions.length, 0)
  const answeredQuestions = Object.keys(responses).length
  const pct = Math.round((answeredQuestions / totalQuestions) * 100)

  const exportCSV = () => {
    const rows = [
      ['ThemisIQ — Supplier Sustainability Response'],
      ['Supplier', supplier?.supplier_name],
      ['Email', supplier?.supplier_email],
      ['Status', supplier?.status],
      ['Completed', supplier?.completed_at ? new Date(supplier.completed_at).toLocaleDateString() : '—'],
      ['Completion', `${pct}%`],
      [''],
      // The id travels next to the wording: labels can be reworded, ids are stable, so
      // two exports of the same data stay reconcilable. Same argument as
      // source_file_path on the verifier surface.
      ['Section', 'Question ID', 'Question', 'Response'],
      ...sections.flatMap(sec =>
        sec.questions.map(q => [sec.title, q.id, q.label, responses[q.id] || 'Not answered'])
      ),
      [''],
      ['Generated by ThemisIQ · www.themisiq.co'],
    ]
    const csv = rows.map(r => r.map(cell => `"${String(cell ?? '').replace(/"/g, '""')}"`).join(',')).join('\n')
    const blob = new Blob([csv], { type: 'text/csv' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${supplier?.supplier_name}_SustainabilityResponse.csv`
    a.click()
  }

  if (loading) return (
    <div style={{ fontFamily: '-apple-system, sans-serif', background: '#f8f7f5', minHeight: '100vh' }}>
      <Nav />
      <div style={{ textAlign: 'center', padding: '4rem', color: '#888784' }}>Loading responses...</div>
    </div>
  )

  if (!isPaid) return <PaywallCard title="Unlock the Supply Chain module" body="The Supplier Portal is part of the Supply Chain module. Unlock it to create campaigns, invite suppliers, and review responses." href="/pricing?modules=supply" />
  return (
    <div style={{ fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif', background: '#f8f7f5', minHeight: '100vh' }}>
      <Nav />

      {/* Header */}
      <div style={{ background: '#fff', borderBottom: '0.5px solid #e8e7e4', padding: '1.5rem 2.5rem' }}>
        <div style={{ maxWidth: 900, margin: '0 auto' }}>
          <button onClick={() => router.push(`/dashboard/supply-chain/portal/${campaignId}`)} style={{ fontSize: 12, color: '#888784', background: 'none', border: 'none', cursor: 'pointer', padding: 0, marginBottom: 8 }}>← Back to campaign</button>
          <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 16 }}>
            <div>
              <div style={{ fontFamily: 'var(--font-display)', fontSize: '1.4rem', fontWeight: 400, color: '#0d0d0d', marginBottom: 4 }}>{supplier?.supplier_name}</div>
              <div style={{ fontSize: 13, color: '#888784' }}>{supplier?.supplier_email}</div>
              {supplier?.contact_name && <div style={{ fontSize: 13, color: '#888784' }}>{supplier.contact_name}</div>}
            </div>
            <div style={{ display: 'flex', gap: 10, alignItems: 'center', flexShrink: 0 }}>
              <span style={{ fontSize: 11, fontWeight: 700, padding: '4px 12px', borderRadius: 99, background: supplier?.status === 'completed' ? '#E1F5EE' : '#FEF3E2', color: supplier?.status === 'completed' ? '#0F6E56' : 'var(--color-module-climate)' }}>
                {supplier?.status === 'completed' ? '✓ Completed' : 'In progress'}
              </span>
              <button onClick={exportCSV} style={{ fontSize: 12, fontWeight: 500, padding: '8px 16px', borderRadius: 8, background: GRAD, color: 'var(--color-on-dark)', border: 'none', cursor: 'pointer' }}>
                ⬇ Export CSV
              </button>
            </div>
          </div>
        </div>
      </div>

      <div style={{ maxWidth: 900, margin: '0 auto', padding: '2rem 2.5rem' }}>

        {/* Completion summary */}
        <div style={{ background: '#0d0d0d', borderRadius: 14, padding: '1.25rem 1.5rem', marginBottom: 20, display: 'flex', alignItems: 'center', gap: '2rem' }}>
          <div style={{ textAlign: 'center', flexShrink: 0 }}>
            <div style={{ fontFamily: 'var(--font-display)', fontSize: '2.5rem', fontWeight: 400, color: pct >= 80 ? '#64fe3e' : pct >= 50 ? '#fde68a' : '#f87171', lineHeight: 1 }}>{pct}%</div>
            <div style={{ fontSize: 11, color: 'rgba(255,255,255,0.4)', marginTop: 4 }}>complete</div>
          </div>
          <div style={{ flex: 1 }}>
            <div style={{ height: 6, background: 'rgba(255,255,255,0.1)', borderRadius: 99, overflow: 'hidden', marginBottom: 10 }}>
              <div style={{ height: '100%', width: `${pct}%`, background: GRAD, borderRadius: 99 }} />
            </div>
            <div style={{ fontSize: 12, color: 'rgba(255,255,255,0.5)' }}>
              {answeredQuestions} of {totalQuestions} questions answered
              {supplier?.completed_at && ` · Submitted ${new Date(supplier.completed_at).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}`}
            </div>
          </div>
          {/* Section scores */}
          <div style={{ display: 'flex', gap: 8, flexShrink: 0 }}>
            {sections.map(sec => {
              const secAnswered = sec.questions.filter(q => responses[q.id]).length
              const secPct = Math.round((secAnswered / sec.questions.length) * 100)
              return (
                <div key={sec.id} style={{ textAlign: 'center' }}>
                  <div style={{ fontSize: 12, fontWeight: 600, color: sec.color }}>{secPct}%</div>
                  <div style={{ fontSize: 9, color: 'rgba(255,255,255,0.3)', marginTop: 2 }}>{sec.title.split(' ')[0]}</div>
                </div>
              )
            })}
          </div>
        </div>

        {/* Section tabs */}
        <div style={{ display: 'grid', gridTemplateColumns: `repeat(${sections.length}, 1fr)`, gap: 8, marginBottom: 20 }}>
          {sections.map((sec, i) => {
            const secAnswered = sec.questions.filter(q => responses[q.id]).length
            const isActive = activeSection === i
            return (
              <button key={sec.id} onClick={() => setActiveSection(i)} style={{ padding: '0.75rem', borderRadius: 10, border: `1.5px solid ${isActive ? sec.color : '#e8e7e4'}`, background: isActive ? sec.bg : '#fff', cursor: 'pointer', textAlign: 'left' }}>
                <div style={{ fontSize: 12, fontWeight: 600, color: isActive ? sec.color : '#0d0d0d', marginBottom: 3 }}>{sec.title}</div>
                <div style={{ fontSize: 10, color: '#888784' }}>{secAnswered}/{sec.questions.length} answered</div>
              </button>
            )
          })}
        </div>

        {/* Responses */}
        <div style={{ background: '#fff', border: '0.5px solid #e8e7e4', borderRadius: 16, overflow: 'hidden' }}>
          <div style={{ background: sections[activeSection]?.bg, padding: '12px 20px', borderBottom: `2px solid ${sections[activeSection]?.color}` }}>
            <div style={{ fontSize: 13, fontWeight: 600, color: sections[activeSection]?.color }}>{sections[activeSection]?.title}</div>
          </div>
          {sections[activeSection]?.questions.map((q, i) => {
            const response = responses[q.id]
            const responseColor = response ? getResponseColor(response) : '#888784'
            return (
              <div key={q.id} style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, padding: '14px 20px', borderBottom: i < sections[activeSection].questions.length - 1 ? '0.5px solid #f3f4f6' : 'none', alignItems: 'center' }}>
                <div style={{ fontSize: 13, color: '#555553', fontWeight: 400 }}>{q.label}</div>
                <div>
                  {response ? (
                    <span style={{ fontSize: 12, fontWeight: 500, color: responseColor, background: `color-mix(in srgb, ${responseColor} 8%, transparent)`, padding: '4px 10px', borderRadius: 99, border: `0.5px solid color-mix(in srgb, ${responseColor} 20%, transparent)` }}>
                      {response}
                    </span>
                  ) : (
                    <span style={{ fontSize: 12, color: '#9ca3af', fontStyle: 'italic' }}>Not answered</span>
                  )}
                </div>
              </div>
            )
          })}
        </div>

      </div>
    </div>
  )
}
