// robots.txt, generated by Next's MetadataRoute.Robots export. Served at /robots.txt.
//
// Trailing slashes are load-bearing. Disallow matches as a string prefix, so '/deals/'
// hides the token children while leaving the public /deals marketing page indexable.
// The same applies to /survey/, /supplier/, /verify/, /verify-cbam/, /impact/ and
// /get-started/, none of which has a bare public page.
//
// Blocking the token paths is a courtesy to well-behaved crawlers, not access control.
// Those URLs carry a credential and are protected by not being linked, not by this file.

import type { MetadataRoute } from 'next'
import { SITE_ORIGIN } from '../lib/siteOrigin'

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: '*',
      allow: '/',
      disallow: [
        '/dashboard',
        // BR8: the Bill Review specialist page. Not access control (its data is behind requireStaffRole); a courtesy.
        '/staff',
        '/login',
        '/signup',
        '/checkout',
        '/order',
        '/forgot-password',
        '/reset-password',
        '/get-started/',
        '/survey/',
        '/supplier/',
        '/verify/',
        '/verify-cbam/',
        '/impact/',
        '/deals/',
      ],
    },
    sitemap: `${SITE_ORIGIN}/sitemap.xml`,
  }
}
