-- mr_industry_opportunities: seed the 12 sectors beyond manuf (60 values)
insert into public.mr_industry_opportunities (industry_code, opportunity_category, relevance, sort_order) values
  ('energy',       'resource_efficiency', 2, 1), ('energy',       'energy_source', 3, 2), ('energy',       'products_services', 3, 3), ('energy',       'markets', 3, 4), ('energy',       'resilience', 2, 5),
  ('extract',      'resource_efficiency', 2, 1), ('extract',      'energy_source', 2, 2), ('extract',      'products_services', 2, 3), ('extract',      'markets', 3, 4), ('extract',      'resilience', 1, 5),
  ('transport',    'resource_efficiency', 3, 1), ('transport',    'energy_source', 3, 2), ('transport',    'products_services', 2, 3), ('transport',    'markets', 2, 4), ('transport',    'resilience', 1, 5),
  ('construction', 'resource_efficiency', 2, 1), ('construction', 'energy_source', 2, 2), ('construction', 'products_services', 3, 3), ('construction', 'markets', 3, 4), ('construction', 'resilience', 2, 5),
  ('  ('  ('  ('  ('  ('  ('  ('  ('  ('  ('  ('  ('  ('  ('  ('  ('  ('  ('urce', 2, 2), ('agri',         'products_services', 3, 3), ('agri',         'markets', 3, 4), ('agri',         'resi  ('  ('  ('  ('  ('  ('  ('  ('  ('  ('  ('  ('  ('  ('  ('  ('  ('  ('  ('urce', 2, 2), ('agri',         'products_services', 3, 3), ('agri',         'markets', 3, 4), ('agri',         'resi  ('  ('  ('  si  ('  ('  ('  ('  ('  ('  ('  ('  ('  ('  ('  ('  ('  ('  ('  ('  ('  ('  ('urce', 2, 2), ('agri',         'products_services', 3, 3), ('agri',         'markets', 3, 4), ('agri',         'resi  ('  ('  ('  silience', 1, 5),
  ('finance',      'resource_efficiency', 1, 1), ('finance',      'energy_source', 1, 2), ('finance',      'products_services', 3, 3), ('finance',      'markets', 3, 4), ('finance',      'resilience', 2, 5),
  ('tech',         'resource_efficiency', 2, 1), ('tech',         'energy_source', 2, 2), ('tech',         'products_services', 3, 3), ('tech',         'markets', 3, 4), ('tech',         'resi  ('tech',         'resource_efficiency', 2, 1), ('tech',         'energy_source', 2, 2), ('tech',         'products_services', 3, 3), ('tech',         'markets', 3, 4), ('tech',         'resi  ('tech',         'resource_efficiency', 2, 1), ('tech',         'energy_source', 2, 2), ('tech',         'products_services', 3, 3), ('tech',         'markets', 3, 4), ('tech',         'resi  ('tech',         'resource_efficiency', 2, 1), ('tech',         'energy_source', 2, 2), ('tech',         'products_services', 3, 3), ('tech',         'markets', 3, 4), ('tech',         'resi  ('tech',         'resource_efficiency', 2, 1silience', 1, 5)
on conflict (industry_code, opportunity_category) do update
  set relevance = excluded.relevance, sort_order = excluded.sort_order;
