// ── DCCEEW NGA 2026: TRANSPORT FUELS (TABLE 9) AND NON-ROAD (TABLE 8) ─────────────────────────────────────
//
// T3d (reporting year 2026). Read cell by cell from ~/themisiq-sources/nga/national-greenhouse-accounts-factors-2026.xlsx
// (sheets "Table 9" and "Table 8") and checked against the PDF (Table 9, pp. 27 to 28, the pre-2004 note on p. 29, PDF
// only, so its rows have no cell; Table 8, pp. 23 to 24). The same rows, mapping and units as nga2025.ts. Every value
// equals 2025's.
//
// ⚠️ NO HEAVY-DUTY PETROL ROW. NGA 2026 Table 9's heavy-duty rows are CNG, LNG, diesel (Euro iv or higher, iii, i) and
// renewable diesel. nga2025.ts takes heavy petrol from the NGER (Measurement) Determination 2008, Compilation No. 21 (1 July
// 2026); that document is not this edition's and was not transcribed for 2026. So a heavy petrol line on NGA 2026 takes
// R16's stated fallback (select.ts): CH4 and N2O from IPCC 2006 Vol. 2 Ch. 3, CO2 from this edition's Table 9, and the row
// says so, as for NGA 2023 and 2024.
// NON-ROAD: the basis is the Determination's definition of stationary energy purposes (s 2.41(2)), quoted as in
// nga2025.ts; it decides which table applies, not a value. The values are NGA 2026 Table 8's.

import type { MobileGasRow, MobilePublisher } from './types'

/** Energy content, GJ per kL, as Table 9 prints it (column "Energy Content factor"). */
export const NGA_MOBILE_ENERGY_CONTENT_2026 = {petrol: {value: 34.2,unit: "GJ/kL",cite: {table: "Table 9 Direct (scope 1) and indirect (scope 3) emission factors for the consumption of transport fuels in different transport equipment",row: "Cars and light commercial vehicles, Gasoline",column: "Energy Content factor (GJ per unit of fuel)",page: "27",cell: "'Table 9'!C5"}},diesel: {value: 38.6,unit: "GJ/kL",cite: {table: "Table 9 Direct (scope 1) and indirect (scope 3) emission factors for the consumption of transport fuels in different transport equipment",row: "Cars and light commercial vehicles, Diesel oil (and every Heavy duty diesel row: Euro iv or higher, Euro iii, Euro i, all 38.6, p.28, 'Table 9'!C17:C19)",column: "Energy Content factor (GJ per unit of fuel)",page: "27",cell: "'Table 9'!C6"}}}

export const NGA_MOBILE_2026: MobilePublisher = {
  publisher: 'DCCEEW National Greenhouse Accounts Factors',
  edition: '2026',
  document: 'DCCEEW (2026) National Greenhouse Accounts Factors 2026',
  co2: [
    {fuel: "petrol",value: 67.4,unit: "kg CO2-e/GJ",cite: {table: "Table 9 Direct (scope 1) and indirect (scope 3) emission factors for the consumption of transport fuels in different transport equipment",row: "Cars and light commercial vehicles, Gasoline",column: "Scope 1 Emission Factor CO2",page: "27",cell: "'Table 9'!D5"}},
    {fuel: "diesel",value: 69.9,unit: "kg CO2-e/GJ",cite: {table: "Table 9 Direct (scope 1) and indirect (scope 3) emission factors for the consumption of transport fuels in different transport equipment",row: "Cars and light commercial vehicles, Diesel oil (and every Heavy duty diesel row, p.28, 'Table 9'!D17:D19, all printed 69.9)",column: "Scope 1 Emission Factor CO2",page: "27",cell: "'Table 9'!D6"}},
  ],
  rows: ([
    {fuel: "petrol",type: "light",vehicle: "Cars and light commercial vehicles",detail: "manufactured 2004 or later",ch4: 0.02,n2o: 0.2,unit: "kg CO2-e/GJ",gas: "co2e_ar5",years: {from: 2004,to: null},cite: {table: "Table 9 Direct (scope 1) and indirect (scope 3) emission factors for the consumption of transport fuels in different transport equipment",row: "Cars and light commercial vehicles, Gasoline, manufactured 2004 or later",column: "Scope 1 Emission Factor (kg CO2-e/GJ): CH4, N2O",page: "27",cell: "'Table 9'!E5, F5"}},
    {fuel: "petrol",type: "light",vehicle: "Cars and light commercial vehicles",detail: "manufactured prior to 2004",ch4: 0.6,n2o: 1.6,unit: "kg CO2-e/GJ",gas: "co2e_ar5",years: {from: null,to: 2003},cite: {table: "Table 9 Direct (scope 1) and indirect (scope 3) emission factors for the consumption of transport fuels in different transport equipment, notes",row: "Cars and light commercial vehicles, Gasoline, manufactured prior to 2004",column: "Scope 1 Emission Factor (kg CO2-e/GJ): CH4, N2O",page: "29",cell_note: "The pre-2004 note is printed in the PDF only (p.29); the workbook \"Table 9\" sheet carries the asterisks on E5:F7, E9:F9, E11:F11 but not the note text."}},
    {fuel: "diesel",type: "light",vehicle: "Cars and light commercial vehicles",detail: "manufactured 2004 or later",ch4: 0.01,n2o: 0.5,unit: "kg CO2-e/GJ",gas: "co2e_ar5",years: {from: 2004,to: null},cite: {table: "Table 9 Direct (scope 1) and indirect (scope 3) emission factors for the consumption of transport fuels in different transport equipment",row: "Cars and light commercial vehicles, Diesel oil, manufactured 2004 or later",column: "Scope 1 Emission Factor (kg CO2-e/GJ): CH4, N2O",page: "27",cell: "'Table 9'!E6, F6"}},
    {fuel: "diesel",type: "light",vehicle: "Cars and light commercial vehicles",detail: "manufactured prior to 2004",ch4: 0.1,n2o: 0.4,unit: "kg CO2-e/GJ",gas: "co2e_ar5",years: {from: null,to: 2003},cite: {table: "Table 9 Direct (scope 1) and indirect (scope 3) emission factors for the consumption of transport fuels in different transport equipment, notes",row: "Cars and light commercial vehicles, Diesel oil, manufactured prior to 2004",column: "Scope 1 Emission Factor (kg CO2-e/GJ): CH4, N2O",page: "29",cell_note: "The pre-2004 note is printed in the PDF only (p.29); the workbook \"Table 9\" sheet carries the asterisks on E5:F7, E9:F9, E11:F11 but not the note text."}},
    {fuel: "diesel",type: "heavy",vehicle: "Heavy duty vehicles",detail: "Euro iv or higher",ch4: 0.07,n2o: 0.4,unit: "kg CO2-e/GJ",gas: "co2e_ar5",cite: {table: "Table 9 Direct (scope 1) and indirect (scope 3) emission factors for the consumption of transport fuels in different transport equipment",row: "Heavy duty vehicles, Diesel oil, Euro iv or higher",column: "Scope 1 Emission Factor (kg CO2-e/GJ): CH4, N2O",page: "28",cell: "'Table 9'!E17, F17"}},
    {fuel: "diesel",type: "heavy",vehicle: "Heavy duty vehicles",detail: "Euro iii",ch4: 0.1,n2o: 0.4,unit: "kg CO2-e/GJ",gas: "co2e_ar5",cite: {table: "Table 9 Direct (scope 1) and indirect (scope 3) emission factors for the consumption of transport fuels in different transport equipment",row: "Heavy duty vehicles, Diesel oil, Euro iii",column: "Scope 1 Emission Factor (kg CO2-e/GJ): CH4, N2O",page: "28",cell: "'Table 9'!E18, F18"}},
    {fuel: "diesel",type: "heavy",vehicle: "Heavy duty vehicles",detail: "Euro i",ch4: 0.2,n2o: 0.4,unit: "kg CO2-e/GJ",gas: "co2e_ar5",cite: {table: "Table 9 Direct (scope 1) and indirect (scope 3) emission factors for the consumption of transport fuels in different transport equipment",row: "Heavy duty vehicles, Diesel oil, Euro i",column: "Scope 1 Emission Factor (kg CO2-e/GJ): CH4, N2O",page: "28",cell: "'Table 9'!E19, F19"}},
    {fuel: "petrol",type: "non_road",vehicle: "Equipment not registered for road use (stationary energy purposes)",detail: null,ch4: 0.2,n2o: 0.2,unit: "kg CO2-e/GJ",gas: "co2e_ar5",cite: {table: "Table 8 Direct (Scope 1) and indirect (scope 3) emission factors for the consumption of liquid fuels, including certain petroleum based products for stationary energy purposes",row: "Automotive gasoline/petrol (other than for use as fuel in an aircraft)",column: "Scope 1 Emission Factor (kg CO2-e/GJ): CH4, N2O",page: "24",cell: "'Table 8'!D9, E9",basis: "Determination s 2.41(2), p. 78: \"transport energy purposes includes purposes for which fuel is combusted that consist of any of the following: (a) transport by vehicles registered for road use; (b) rail transport; (c) waterborne transport; (d) air transport\", and \"stationary energy purposes means purposes for which fuel is combusted that do not involve transport energy purposes\"; so equipment not registered for road use takes Schedule 1 Part 3, NGA Table 8 (the 2026 edition titles Table 8 \"for stationary energy purposes\")."}},
    {fuel: "diesel",type: "non_road",vehicle: "Equipment not registered for road use (stationary energy purposes)",detail: null,ch4: 0.1,n2o: 0.2,unit: "kg CO2-e/GJ",gas: "co2e_ar5",cite: {table: "Table 8 Direct (Scope 1) and indirect (scope 3) emission factors for the consumption of liquid fuels, including certain petroleum based products for stationary energy purposes",row: "Diesel oil",column: "Scope 1 Emission Factor (kg CO2-e/GJ): CH4, N2O",page: "24",cell: "'Table 8'!D14, E14",basis: "Determination s 2.41(2), p. 78: \"transport energy purposes includes purposes for which fuel is combusted that consist of any of the following: (a) transport by vehicles registered for road use; (b) rail transport; (c) waterborne transport; (d) air transport\", and \"stationary energy purposes means purposes for which fuel is combusted that do not involve transport energy purposes\"; so equipment not registered for road use takes Schedule 1 Part 3, NGA Table 8 (the 2026 edition titles Table 8 \"for stationary energy purposes\")."}},
  ] as MobileGasRow[]),
  absent: [{ type: 'heavy', fuel: 'petrol', said: null }],
  splitBy: {
    'light:petrol': 'Model year', 'light:diesel': 'Model year', 'heavy:diesel': 'Euro standard',
  },
}
