-- 20260914_exiobase_sectors.sql
--
-- ⚠️ RUN ON 14 SEPTEMBER 2026, IN FULL. DO NOT RUN IT AGAIN.
--
-- All eight blocks were executed and the four verification queries in section 8 passed. This file
-- is now a RECORD of what was done, not a script to run. It is kept executable-looking because the
-- schema it creates has to be reproducible into an empty database, and that is the only situation
-- in which any of it should be executed again.
--
-- ⚠️ SECTION 5 TRUNCATES supply_chain_registers, scope3_inventories, supplier_responses AND
-- campaign_suppliers. When it ran, those tables held one register named TEST, one scope3 row and
-- twelve campaign suppliers, all pre-launch. A second run against a live database would delete
-- every customer register, every saved Scope 3 inventory and every supplier response, with no
-- undo. If you are re-establishing this schema on an empty database, read section 5 before you
-- start and satisfy yourself the counts are what its own pre-flight query expects.
--
-- One thing HAS changed since the run: the row fingerprint below moved from 505866da... to
-- b393d1ad... when lib/emissionFactors/exiobaseSectors.json gained display_group and a groups
-- array on 14 September 2026. The live reference_data_fingerprints row was updated by a standalone
-- statement rather than by re-running any part of this file. The values seeded in sections 1 to 3
-- did not change: the generator now READS the display groups from this migration, so the file and
-- the database agree by construction.
--
-- The sector vocabulary becomes EXIOBASE's own. Three tables' worth of internal sector strings
-- become foreign keys into a seeded reference table, and the display groupings the UI needs become
-- data rather than an array in a page component.
--
-- ── WHY THIS IS A SCHEMA CHANGE AND A TRUNCATE, NOT A MIGRATION ──────────────────────────────
--
-- There WAS no customer data when this ran. One supply_chain_registers row named TEST, one
-- scope3_inventories row, twelve campaign_suppliers rows, all pre-launch. So the sector strings
-- already stored were discarded rather than mapped, and the constraints below were added outright
-- instead of backfilled behind a nullable column. Section 5 does the truncate; nothing here is
-- reversible once it runs, and nothing here may be run once a real customer row exists.
--
-- ── FIVE DECISIONS WORTH FINDING HERE RATHER THAN INFERRING ──────────────────────────────────
--
--   · ONE TABLE FOR INDUSTRIES AND PRODUCTS, NOT TWO. EXIOBASE publishes 163 industries and 200
--     products, and lib/emissionFactors/spend.ts already carries factor_type ('industry' |
--     'product') as a required discriminator on every factor record. Two tables would put that
--     discriminator in the table NAME, where a foreign key cannot see it: a column holding "an
--     EXIOBASE sector" would need two nullable FKs and a CHECK that exactly one is set, and every
--     query would union. One table with factor_type as a column keeps the discriminator in the
--     data, which is where spend.ts says it belongs.
--
--   · exio_code IS THE PRIMARY KEY, SINGLE-COLUMN, AND THAT IS SAFE BY VERIFICATION NOT BY LUCK.
--     Industry codes all begin 'i' and product codes all begin 'p'; the two sets were checked for
--     collisions and share none, so 363 codes are globally distinct. A composite (factor_type,
--     exio_code) key would be more obviously correct but would force every referencing column to
--     carry a redundant factor_type alongside it. The prefix CHECK below is what keeps the
--     single-column key honest: it makes factor_type and the code unable to disagree.
--
--   · DISPLAY GROUPS ARE A SEPARATE TABLE, DELIBERATELY. They are OUR headings for OUR dropdowns,
--     grouped on what the EXIOBASE name strings say. They are not a classification, they are not
--     derived from ISIC or NACE, and no figure is computed from them. Keeping them out of the
--     sector table and naming the table sector_display_groups is what stops the next reader
--     treating them as provenance. The table comment says so in as many words.
--
--   · isic_code AND isic_name ARE NULLABLE, AND ONLY FOR PRODUCTS. EXIOBASE's product table
--     carries no ISIC column at all. A NOT NULL with a placeholder would assert a classification
--     the publisher does not publish; the CHECK below requires them on industries and forbids
--     them on products, so absence stays a fact rather than a gap.
--
--   · THE JSONB SECTOR PATHS GET A TRIGGER, NOT A CHECK. A CHECK constraint cannot contain a
--     subquery, so it cannot ask whether a sector inside a jsonb array exists in this table. See
--     the note above section 5 for what that means and what the trigger does instead.
--
-- Source: lib/emissionFactors/exiobaseSectors.json, itself generated by
-- scripts/generate-exiobase-sectors.py from pymrio 0.6.3's bundled EXIOBASE 3 classification.
-- EXIOBASE 3 v3.8.2, DOI 10.5281/zenodo.5589597, CC BY-SA 4.0. The ShareAlike term attaches
-- obligations to anything published from this; see lib/emissionFactors/spend.ts.


-- ═══ 1. DISPLAY GROUPS ═══════════════════════════════════════════════════════════════════════

create table if not exists public.sector_display_groups (
  id            integer primary key,
  heading       text    not null unique,
  member_count  integer not null,
  created_at    timestamptz not null default now()
);

comment on table public.sector_display_groups is
  'PRESENTATION ONLY. Headings used to group the EXIOBASE industry list in ThemisIQ dropdowns so a '
  '163-item select is navigable. These are NOT a classification: they are not published by anyone, '
  'they are not derived from ISIC or NACE, they carry no methodological claim, and no emission '
  'figure is computed from them. Membership was assigned by reading what the EXIOBASE name strings '
  'say. The published classification lives in exiobase_sectors.isic_code / isic_name; if the two '
  'ever disagree, the published one is right and this one is a UI decision.';

comment on column public.sector_display_groups.member_count is
  'Industries in this group at seed time. Denormalised for review only - the authority is the count '
  'of exiobase_sectors rows carrying this heading. A disagreement means the seed is stale.';

insert into public.sector_display_groups (id, heading, member_count) values
  (1, 'Food, drink & tobacco', 12),
  (2, 'Textiles, clothing & leather', 3),
  (3, 'Wood, paper & print', 6),
  (4, 'Fuels & chemicals', 9),
  (5, 'Non-metallic minerals', 7),
  (6, 'Metals & metal products', 14),
  (7, 'Machinery, electronics & vehicles', 8),
  (8, 'Waste, recycling & water treatment', 22),
  (9, 'Education, health & other services', 5),
  (10, 'Agriculture & horticulture', 17),
  (11, 'Forestry & logging', 1),
  (12, 'Fishing', 1),
  (13, 'Mining & quarrying', 15),
  (14, 'Electricity, gas & water supply', 17),
  (15, 'Construction', 2),
  (16, 'Wholesale, retail & hospitality', 5),
  (17, 'Transport, storage & communications', 8),
  (18, 'Finance, real estate & business services', 8),
  (19, 'Public administration & defence', 2),
  (20, 'Households as employers', 1)on conflict (id) do nothing;


-- ═══ 2. THE SECTOR TABLE ═════════════════════════════════════════════════════════════════════

create table if not exists public.exiobase_sectors (
  exio_code             text    primary key,
  factor_type           text    not null check (factor_type in ('industry', 'product')),
  exio_number           integer not null,
  exio_name             text    not null,
  exio_label            text    not null,
  isic_code             text,
  isic_name             text,
  consumption_category  text    not null,
  display_group         text    references public.sector_display_groups (heading),
  product_type          text,

  -- The prefix is what lets exio_code be a single-column key without factor_type becoming
  -- decorative. A row claiming to be an industry with a 'p' code, or the reverse, cannot exist.
  constraint exiobase_sectors_code_matches_type check (
    (factor_type = 'industry' and exio_code like 'i%') or
    (factor_type = 'product'  and exio_code like 'p%')
  ),

  -- Industries carry ISIC and a display group; products carry neither and carry a product type
  -- instead. Absence is a fact about what EXIOBASE publishes, not a gap to be filled.
  constraint exiobase_sectors_industry_fields check (
    factor_type <> 'industry' or
    (isic_code is not null and isic_name is not null and display_group is not null
     and product_type is null)
  ),
  constraint exiobase_sectors_product_fields check (
    factor_type <> 'product' or
    (isic_code is null and isic_name is null and display_group is null
     and product_type is not null)
  ),

  constraint exiobase_sectors_number_per_type unique (factor_type, exio_number),
  constraint exiobase_sectors_label_unique unique (exio_label)
);

comment on table public.exiobase_sectors is
  'EXIOBASE 3 v3.8.2 sector classification: 163 industries (ixi) and 200 products (pxp). '
  'Seeded from lib/emissionFactors/exiobaseSectors.json, generated by '
  'scripts/generate-exiobase-sectors.py from pymrio 0.6.3. DOI 10.5281/zenodo.5589597, '
  'CC BY-SA 4.0 - attribution and ShareAlike apply to anything published from it. '
  'CLASSIFICATION ONLY: this table holds NO emission factors. The isic_code values are ISIC '
  'Rev. 3.1 style SECTION labels (12 distinct across 163 industries, three of them pre-aggregated '
  'multi-section buckets), consistent with the v3.8.2 readme stating the database is on NACE '
  'Rev. 1.1. They are a grouping, not a crosswalk, and cannot resolve an ISIC code back to an '
  'EXIOBASE industry.';

comment on column public.exiobase_sectors.display_group is
  'OUR heading for OUR dropdowns. Presentation only - see sector_display_groups. Null on products, '
  'which have no grouped UI today.';

create index if not exists exiobase_sectors_type_idx    on public.exiobase_sectors (factor_type);
create index if not exists exiobase_sectors_group_idx   on public.exiobase_sectors (display_group);
create index if not exists exiobase_sectors_isic_idx    on public.exiobase_sectors (isic_code);


-- ═══ 3. SEED — 363 ROWS, GENERATED ═══════════════════════════════════════════════════════════
--
-- Do not hand-edit these values. They are a transcription of
-- lib/emissionFactors/exiobaseSectors.json, whose row fingerprint is sha256
-- b393d1ad7d4966cd0ddd7c29379c98b362ab9bed01be7e98afd53226647e3341
-- (pinned in lib/emissionFactors/exiobaseSectors.test.ts as ROWS_SHA256). If the JSON changes,
-- regenerate this block rather than editing it. See section 7 on how the two stay in step.
--
-- Two names below are misspelled: 'preciuos metals' (i27.41.w) and 'sewage slugde' (i90.2.c).
-- They are EXIOBASE's own typos and are carried verbatim. Correcting them here would put a string
-- in the database that does not match the published classification or the JSON.

insert into public.exiobase_sectors
  (factor_type, exio_code, exio_number, exio_name, exio_label,
   isic_code, isic_name, consumption_category, display_group, product_type)
values
  ('industry', 'i01.a', 1, 'Cultivation of paddy rice', 'A_PARI', 'ISIC_A', 'Agriculture, hunting and related service activities (01)', 'Food', 'Agriculture & horticulture', null),
  ('industry', 'i01.b', 2, 'Cultivation of wheat', 'A_WHEA', 'ISIC_A', 'Agriculture, hunting and related service activities (01)', 'Food', 'Agriculture & horticulture', null),
  ('industry', 'i01.c', 3, 'Cultivation of cereal grains nec', 'A_OCER', 'ISIC_A', 'Agriculture, hunting and related service activities (01)', 'Food', 'Agriculture & horticulture', null),
  ('industry', 'i01.d', 4, 'Cultivation of vegetables, fruit, nuts', 'A_FVEG', 'ISIC_A', 'Agriculture, hunting and related service activities (01)', 'Food', 'Agriculture & horticulture', null),
  ('industry', 'i01.e', 5, 'Cultivation of oil seeds', 'A_OILS', 'ISIC_A', 'Agriculture, hunting and related service activities (01)', 'Food', 'Agriculture & horticulture', null),
  ('industry', 'i01.f', 6, 'Cultivation of sugar cane, sugar beet', 'A_SUGB', 'ISIC_A', 'Agriculture, hunting and related service activities (01)', 'Food', 'Agriculture & horticulture', null),
  ('industry', 'i01.g', 7, 'Cultivation of plant-based fibers', 'A_FIBR', 'ISIC_A', 'Agriculture, hunting and related service activities (01)', 'Food', 'Agriculture & horticulture', null),
  ('industry', 'i01.h', 8, 'Cultivation of crops nec', 'A_OTCR', 'ISIC_A', 'Agriculture, hunting and related service activities (01)', 'Food', 'Agriculture & horticulture', null),
  ('industry', 'i01.i', 9, 'Cattle farming', 'A_CATL', 'ISIC_A', 'Agriculture, hunting and related service activities (01)', 'Food', 'Agriculture & horticulture', null),
  ('industry', 'i01.j', 10, 'Pigs farming', 'A_PIGS', 'ISIC_A', 'Agriculture, hunting and related service activities (01)', 'Food', 'Agriculture & horticulture', null),
  ('industry', 'i01.k', 11, 'Poultry farming', 'A_PLTR', 'ISIC_A', 'Agriculture, hunting and related service activities (01)', 'Food', 'Agriculture & horticulture', null),
  ('industry', 'i01.l', 12, 'Meat animals nec', 'A_OMEA', 'ISIC_A', 'Agriculture, hunting and related service activities (01)', 'Food', 'Agriculture & horticulture', null),
  ('industry', 'i01.m', 13, 'Animal products nec', 'A_OANP', 'ISIC_A', 'Agriculture, hunting and related service activities (01)', 'Food', 'Agriculture & horticulture', null),
  ('industry', 'i01.n', 14, 'Raw milk', 'A_MILK', 'ISIC_A', 'Agriculture, hunting and related service activities (01)', 'Food', 'Agriculture & horticulture', null),
  ('industry', 'i01.o', 15, 'Wool, silk-worm cocoons', 'A_WOOL', 'ISIC_A', 'Agriculture, hunting and related service activities (01)', 'Clothing', 'Agriculture & horticulture', null),
  ('industry', 'i01.w.1', 16, 'Manure treatment (conventional), storage and land application', 'A_MANC', 'ISIC_A', 'Agriculture, hunting and related service activities (01)', 'Food', 'Agriculture & horticulture', null),
  ('industry', 'i01.w.2', 17, 'Manure treatment (biogas), storage and land application', 'A_MANB', 'ISIC_A', 'Agriculture, hunting and related service activities (01)', 'Food', 'Agriculture & horticulture', null),
  ('industry', 'i02', 18, 'Forestry, logging and related service activities (02)', 'A_FORE', 'ISIC_A', 'Forestry, logging and related service activities (02)', 'Shelter', 'Forestry & logging', null),
  ('industry', 'i05', 19, 'Fishing, operating of fish hatcheries and fish farms; service activities incidental to fishing (05)', 'A_FISH', 'ISIC_B', 'Fishing (B)', 'Food', 'Fishing', null),
  ('industry', 'i10', 20, 'Mining of coal and lignite; extraction of peat (10)', 'A_COAL', 'ISIC_C', 'Mining and quarrying (C)', 'Shelter', 'Mining & quarrying', null),
  ('industry', 'i11.a', 21, 'Extraction of crude petroleum and services related to crude oil extraction, excluding surveying', 'A_COIL', 'ISIC_C', 'Mining and quarrying (C)', 'Shelter', 'Mining & quarrying', null),
  ('industry', 'i11.b', 22, 'Extraction of natural gas and services related to natural gas extraction, excluding surveying', 'A_GASE', 'ISIC_C', 'Mining and quarrying (C)', 'Shelter', 'Mining & quarrying', null),
  ('industry', 'i11.c', 23, 'Extraction, liquefaction, and regasification of other petroleum and gaseous materials', 'A_OGPL', 'ISIC_C', 'Mining and quarrying (C)', 'Shelter', 'Mining & quarrying', null),
  ('industry', 'i12', 24, 'Mining of uranium and thorium ores (12)', 'A_ORAN', 'ISIC_C', 'Mining and quarrying (C)', 'Shelter', 'Mining & quarrying', null),
  ('industry', 'i13.1', 25, 'Mining of iron ores', 'A_IRON', 'ISIC_C', 'Mining and quarrying (C)', 'Shelter', 'Mining & quarrying', null),
  ('industry', 'i13.20.11', 26, 'Mining of copper ores and concentrates', 'A_COPO', 'ISIC_C', 'Mining and quarrying (C)', 'Construction', 'Mining & quarrying', null),
  ('industry', 'i13.20.12', 27, 'Mining of nickel ores and concentrates', 'A_NIKO', 'ISIC_C', 'Mining and quarrying (C)', 'Construction', 'Mining & quarrying', null),
  ('industry', 'i13.20.13', 28, 'Mining of aluminium ores and concentrates', 'A_ALUO', 'ISIC_C', 'Mining and quarrying (C)', 'Construction', 'Mining & quarrying', null),
  ('industry', 'i13.20.14', 29, 'Mining of precious metal ores and concentrates', 'A_PREO', 'ISIC_C', 'Mining and quarrying (C)', 'Construction', 'Mining & quarrying', null),
  ('industry', 'i13.20.15', 30, 'Mining of lead, zinc and tin ores and concentrates', 'A_LZTO', 'ISIC_C', 'Mining and quarrying (C)', 'Construction', 'Mining & quarrying', null),
  ('industry', 'i13.20.16', 31, 'Mining of other non-ferrous metal ores and concentrates', 'A_ONFO', 'ISIC_C', 'Mining and quarrying (C)', 'Construction', 'Mining & quarrying', null),
  ('industry', 'i14.1', 32, 'Quarrying of stone', 'A_STON', 'ISIC_C', 'Mining and quarrying (C)', 'Construction', 'Mining & quarrying', null),
  ('industry', 'i14.2', 33, 'Quarrying of sand and clay', 'A_SDCL', 'ISIC_C', 'Mining and quarrying (C)', 'Construction', 'Mining & quarrying', null),
  ('industry', 'i14.3', 34, 'Mining of chemical and fertilizer minerals, production of salt, other mining and quarrying n.e.c.', 'A_CHMF', 'ISIC_C', 'Mining and quarrying (C)', 'Food', 'Mining & quarrying', null),
  ('industry', 'i15.a', 35, 'Processing of meat cattle', 'A_PCAT', 'ISIC_D', 'Manufacturing (D)', 'Food', 'Food, drink & tobacco', null),
  ('industry', 'i15.b', 36, 'Processing of meat pigs', 'A_PPIG', 'ISIC_D', 'Manufacturing (D)', 'Food', 'Food, drink & tobacco', null),
  ('industry', 'i15.c', 37, 'Processing of meat poultry', 'A_PPLT', 'ISIC_D', 'Manufacturing (D)', 'Food', 'Food, drink & tobacco', null),
  ('industry', 'i15.d', 38, 'Production of meat products nec', 'A_POME', 'ISIC_D', 'Manufacturing (D)', 'Food', 'Food, drink & tobacco', null),
  ('industry', 'i15.e', 39, 'Processing vegetable oils and fats', 'A_VOIL', 'ISIC_D', 'Manufacturing (D)', 'Food', 'Food, drink & tobacco', null),
  ('industry', 'i15.f', 40, 'Processing of dairy products', 'A_DAIR', 'ISIC_D', 'Manufacturing (D)', 'Food', 'Food, drink & tobacco', null),
  ('industry', 'i15.g', 41, 'Processed rice', 'A_RICE', 'ISIC_D', 'Manufacturing (D)', 'Food', 'Food, drink & tobacco', null),
  ('industry', 'i15.h', 42, 'Sugar refining', 'A_SUGR', 'ISIC_D', 'Manufacturing (D)', 'Food', 'Food, drink & tobacco', null),
  ('industry', 'i15.i', 43, 'Processing of Food products nec', 'A_OFOD', 'ISIC_D', 'Manufacturing (D)', 'Food', 'Food, drink & tobacco', null),
  ('industry', 'i15.j', 44, 'Manufacture of beverages', 'A_BEVR', 'ISIC_D', 'Manufacturing (D)', 'Food', 'Food, drink & tobacco', null),
  ('industry', 'i15.k', 45, 'Manufacture of fish products', 'A_FSHP', 'ISIC_D', 'Manufacturing (D)', 'Food', 'Food, drink & tobacco', null),
  ('industry', 'i16', 46, 'Manufacture of tobacco products (16)', 'A_TOBC', 'ISIC_D', 'Manufacturing (D)', 'Food', 'Food, drink & tobacco', null),
  ('industry', 'i17', 47, 'Manufacture of textiles (17)', 'A_TEXT', 'ISIC_D', 'Manufacturing (D)', 'Clothing', 'Textiles, clothing & leather', null),
  ('industry', 'i18', 48, 'Manufacture of wearing apparel; dressing and dyeing of fur (18)', 'A_GARM', 'ISIC_D', 'Manufacturing (D)', 'Clothing', 'Textiles, clothing & leather', null),
  ('industry', 'i19', 49, 'Tanning and dressing of leather; manufacture of luggage, handbags, saddlery, harness and footwear (19)', 'A_LETH', 'ISIC_D', 'Manufacturing (D)', 'Clothing', 'Textiles, clothing & leather', null),
  ('industry', 'i20', 50, 'Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials (20)', 'A_WOOD', 'ISIC_D', 'Manufacturing (D)', 'Shelter', 'Wood, paper & print', null),
  ('industry', 'i20.w', 51, 'Re-processing of secondary wood material into new wood material', 'A_WOOW', 'ISIC_D', 'Manufacturing (D)', 'Shelter', 'Wood, paper & print', null),
  ('industry', 'i21.1', 52, 'Pulp', 'A_PULP', 'ISIC_D', 'Manufacturing (D)', 'Manufactured_products', 'Wood, paper & print', null),
  ('industry', 'i21.w.1', 53, 'Re-processing of secondary paper into new pulp', 'A_PAPR', 'ISIC_D', 'Manufacturing (D)', 'Manufactured_products', 'Wood, paper & print', null),
  ('industry', 'i21.2', 54, 'Paper', 'A_PAPE', 'ISIC_D', 'Manufacturing (D)', 'Manufactured_products', 'Wood, paper & print', null),
  ('industry', 'i22', 55, 'Publishing, printing and reproduction of recorded media (22)', 'A_MDIA', 'ISIC_D', 'Manufacturing (D)', 'Services', 'Wood, paper & print', null),
  ('industry', 'i23.1', 56, 'Manufacture of coke oven products', 'A_COKE', 'ISIC_D', 'Manufacturing (D)', 'Shelter', 'Fuels & chemicals', null),
  ('industry', 'i23.2', 57, 'Petroleum Refinery', 'A_REFN', 'ISIC_D', 'Manufacturing (D)', 'Mobility', 'Fuels & chemicals', null),
  ('industry', 'i23.3', 58, 'Processing of nuclear fuel', 'A_NUCF', 'ISIC_D', 'Manufacturing (D)', 'Shelter', 'Fuels & chemicals', null),
  ('industry', 'i24.a', 59, 'Plastics, basic', 'A_PLAS', 'ISIC_D', 'Manufacturing (D)', 'Manufactured_products', 'Fuels & chemicals', null),
  ('industry', 'i24.a.w', 60, 'Re-processing of secondary plastic into new plastic', 'A_PLAW', 'ISIC_D', 'Manufacturing (D)', 'Manufactured_products', 'Fuels & chemicals', null),
  ('industry', 'i24.b', 61, 'N-fertiliser', 'A_NFER', 'ISIC_D', 'Manufacturing (D)', 'Food', 'Fuels & chemicals', null),
  ('industry', 'i24.c', 62, 'P- and other fertiliser', 'A_PFER', 'ISIC_D', 'Manufacturing (D)', 'Food', 'Fuels & chemicals', null),
  ('industry', 'i24.d', 63, 'Chemicals nec', 'A_CHEM', 'ISIC_D', 'Manufacturing (D)', 'Manufactured_products', 'Fuels & chemicals', null),
  ('industry', 'i25', 64, 'Manufacture of rubber and plastic products (25)', 'A_RUBP', 'ISIC_D', 'Manufacturing (D)', 'Manufactured_products', 'Fuels & chemicals', null),
  ('industry', 'i26.a', 65, 'Manufacture of glass and glass products', 'A_GLAS', 'ISIC_D', 'Manufacturing (D)', 'Construction', 'Non-metallic minerals', null),
  ('industry', 'i26.a.w', 66, 'Re-processing of secondary glass into new glass', 'A_GLAW', 'ISIC_D', 'Manufacturing (D)', 'Construction', 'Non-metallic minerals', null),
  ('industry', 'i26.b', 67, 'Manufacture of ceramic goods', 'A_CRMC', 'ISIC_D', 'Manufacturing (D)', 'Construction', 'Non-metallic minerals', null),
  ('industry', 'i26.c', 68, 'Manufacture of bricks, tiles and construction products, in baked clay', 'A_BRIK', 'ISIC_D', 'Manufacturing (D)', 'Construction', 'Non-metallic minerals', null),
  ('industry', 'i26.d', 69, 'Manufacture of cement, lime and plaster', 'A_CMNT', 'ISIC_D', 'Manufacturing (D)', 'Construction', 'Non-metallic minerals', null),
  ('industry', 'i26.d.w', 70, 'Re-processing of ash into clinker', 'A_ASHW', 'ISIC_D', 'Manufacturing (D)', 'Construction', 'Non-metallic minerals', null),
  ('industry', 'i26.e', 71, 'Manufacture of other non-metallic mineral products n.e.c.', 'A_ONMM', 'ISIC_D', 'Manufacturing (D)', 'Construction', 'Non-metallic minerals', null),
  ('industry', 'i27.a', 72, 'Manufacture of basic iron and steel and of ferro-alloys and first products thereof', 'A_STEL', 'ISIC_D', 'Manufacturing (D)', 'Manufactured_products', 'Metals & metal products', null),
  ('industry', 'i27.a.w', 73, 'Re-processing of secondary steel into new steel', 'A_STEW', 'ISIC_D', 'Manufacturing (D)', 'Manufactured_products', 'Metals & metal products', null),
  ('industry', 'i27.41', 74, 'Precious metals production', 'A_PREM', 'ISIC_D', 'Manufacturing (D)', 'Manufactured_products', 'Metals & metal products', null),
  ('industry', 'i27.41.w', 75, 'Re-processing of secondary preciuos metals into new preciuos metals', 'A_PREW', 'ISIC_D', 'Manufacturing (D)', 'Manufactured_products', 'Metals & metal products', null),
  ('industry', 'i27.42', 76, 'Aluminium production', 'A_ALUM', 'ISIC_D', 'Manufacturing (D)', 'Manufactured_products', 'Metals & metal products', null),
  ('industry', 'i27.42.w', 77, 'Re-processing of secondary aluminium into new aluminium', 'A_ALUW', 'ISIC_D', 'Manufacturing (D)', 'Manufactured_products', 'Metals & metal products', null),
  ('industry', 'i27.43', 78, 'Lead, zinc and tin production', 'A_LZTP', 'ISIC_D', 'Manufacturing (D)', 'Manufactured_products', 'Metals & metal products', null),
  ('industry', 'i27.43.w', 79, 'Re-processing of secondary lead into new lead, zinc and tin', 'A_LZTW', 'ISIC_D', 'Manufacturing (D)', 'Manufactured_products', 'Metals & metal products', null),
  ('industry', 'i27.44', 80, 'Copper production', 'A_COPP', 'ISIC_D', 'Manufacturing (D)', 'Manufactured_products', 'Metals & metal products', null),
  ('industry', 'i27.44.w', 81, 'Re-processing of secondary copper into new copper', 'A_COPW', 'ISIC_D', 'Manufacturing (D)', 'Manufactured_products', 'Metals & metal products', null),
  ('industry', 'i27.45', 82, 'Other non-ferrous metal production', 'A_ONFM', 'ISIC_D', 'Manufacturing (D)', 'Manufactured_products', 'Metals & metal products', null),
  ('industry', 'i27.45.w', 83, 'Re-processing of secondary other non-ferrous metals into new other non-ferrous metals', 'A_ONFW', 'ISIC_D', 'Manufacturing (D)', 'Manufactured_products', 'Metals & metal products', null),
  ('industry', 'i27.5', 84, 'Casting of metals', 'A_METC', 'ISIC_D', 'Manufacturing (D)', 'Manufactured_products', 'Metals & metal products', null),
  ('industry', 'i28', 85, 'Manufacture of fabricated metal products, except machinery and equipment (28)', 'A_FABM', 'ISIC_D', 'Manufacturing (D)', 'Manufactured_products', 'Metals & metal products', null),
  ('industry', 'i29', 86, 'Manufacture of machinery and equipment n.e.c. (29)', 'A_MACH', 'ISIC_D', 'Manufacturing (D)', 'Manufactured_products', 'Machinery, electronics & vehicles', null),
  ('industry', 'i30', 87, 'Manufacture of office machinery and computers (30)', 'A_OFMA', 'ISIC_D', 'Manufacturing (D)', 'Manufactured_products', 'Machinery, electronics & vehicles', null),
  ('industry', 'i31', 88, 'Manufacture of electrical machinery and apparatus n.e.c. (31)', 'A_ELMA', 'ISIC_D', 'Manufacturing (D)', 'Manufactured_products', 'Machinery, electronics & vehicles', null),
  ('industry', 'i32', 89, 'Manufacture of radio, television and communication equipment and apparatus (32)', 'A_RATV', 'ISIC_D', 'Manufacturing (D)', 'Manufactured_products', 'Machinery, electronics & vehicles', null),
  ('industry', 'i33', 90, 'Manufacture of medical, precision and optical instruments, watches and clocks (33)', 'A_MEIN', 'ISIC_D', 'Manufacturing (D)', 'Manufactured_products', 'Machinery, electronics & vehicles', null),
  ('industry', 'i34', 91, 'Manufacture of motor vehicles, trailers and semi-trailers (34)', 'A_MOTO', 'ISIC_D', 'Manufacturing (D)', 'Manufactured_products', 'Machinery, electronics & vehicles', null),
  ('industry', 'i35', 92, 'Manufacture of other transport equipment (35)', 'A_OTRE', 'ISIC_D', 'Manufacturing (D)', 'Manufactured_products', 'Machinery, electronics & vehicles', null),
  ('industry', 'i36', 93, 'Manufacture of furniture; manufacturing n.e.c. (36)', 'A_FURN', 'ISIC_D', 'Manufacturing (D)', 'Manufactured_products', 'Machinery, electronics & vehicles', null),
  ('industry', 'i37', 94, 'Recycling of waste and scrap', 'A_RYMS', 'ISIC_D', 'Manufacturing (D)', 'Manufactured_products', 'Waste, recycling & water treatment', null),
  ('industry', 'i37.w.1', 95, 'Recycling of bottles by direct reuse', 'A_BOTW', 'ISIC_D', 'Manufacturing (D)', 'Manufactured_products', 'Waste, recycling & water treatment', null),
  ('industry', 'i40.11.a', 96, 'Production of electricity by coal', 'A_POWC', 'ISIC_E', 'Electricity, gas and water supply (E)', 'Shelter', 'Electricity, gas & water supply', null),
  ('industry', 'i40.11.b', 97, 'Production of electricity by gas', 'A_POWG', 'ISIC_E', 'Electricity, gas and water supply (E)', 'Shelter', 'Electricity, gas & water supply', null),
  ('industry', 'i40.11.c', 98, 'Production of electricity by nuclear', 'A_POWN', 'ISIC_E', 'Electricity, gas and water supply (E)', 'Shelter', 'Electricity, gas & water supply', null),
  ('industry', 'i40.11.d', 99, 'Production of electricity by hydro', 'A_POWH', 'ISIC_E', 'Electricity, gas and water supply (E)', 'Shelter', 'Electricity, gas & water supply', null),
  ('industry', 'i40.11.e', 100, 'Production of electricity by wind', 'A_POWW', 'ISIC_E', 'Electricity, gas and water supply (E)', 'Shelter', 'Electricity, gas & water supply', null),
  ('industry', 'i40.11.f', 101, 'Production of electricity by petroleum and other oil derivatives', 'A_POWP', 'ISIC_E', 'Electricity, gas and water supply (E)', 'Shelter', 'Electricity, gas & water supply', null),
  ('industry', 'i40.11.g', 102, 'Production of electricity by biomass and waste', 'A_POWB', 'ISIC_E', 'Electricity, gas and water supply (E)', 'Shelter', 'Electricity, gas & water supply', null),
  ('industry', 'i40.11.h', 103, 'Production of electricity by solar photovoltaic', 'A_POWS', 'ISIC_E', 'Electricity, gas and water supply (E)', 'Shelter', 'Electricity, gas & water supply', null),
  ('industry', 'i40.11.i', 104, 'Production of electricity by solar thermal', 'A_POWE', 'ISIC_E', 'Electricity, gas and water supply (E)', 'Shelter', 'Electricity, gas & water supply', null),
  ('industry', 'i40.11.j', 105, 'Production of electricity by tide, wave, ocean', 'A_POWO', 'ISIC_E', 'Electricity, gas and water supply (E)', 'Shelter', 'Electricity, gas & water supply', null),
  ('industry', 'i40.11.k', 106, 'Production of electricity by Geothermal', 'A_POWM', 'ISIC_E', 'Electricity, gas and water supply (E)', 'Shelter', 'Electricity, gas & water supply', null),
  ('industry', 'i40.11.l', 107, 'Production of electricity nec', 'A_POWZ', 'ISIC_E', 'Electricity, gas and water supply (E)', 'Shelter', 'Electricity, gas & water supply', null),
  ('industry', 'i40.12', 108, 'Transmission of electricity', 'A_POWT', 'ISIC_E', 'Electricity, gas and water supply (E)', 'Shelter', 'Electricity, gas & water supply', null),
  ('industry', 'i40.13', 109, 'Distribution and trade of electricity', 'A_POWD', 'ISIC_E', 'Electricity, gas and water supply (E)', 'Shelter', 'Electricity, gas & water supply', null),
  ('industry', 'i40.2', 110, 'Manufacture of gas; distribution of gaseous fuels through mains', 'A_GASD', 'ISIC_E', 'Electricity, gas and water supply (E)', 'Shelter', 'Electricity, gas & water supply', null),
  ('industry', 'i40.3', 111, 'Steam and hot water supply', 'A_HWAT', 'ISIC_E', 'Electricity, gas and water supply (E)', 'Shelter', 'Electricity, gas & water supply', null),
  ('industry', 'i41', 112, 'Collection, purification and distribution of water (41)', 'A_WATR', 'ISIC_E', 'Electricity, gas and water supply (E)', 'Shelter', 'Electricity, gas & water supply', null),
  ('industry', 'i45', 113, 'Construction (45)', 'A_CONS', 'ISIC_F', 'Construction (F)', 'Construction', 'Construction', null),
  ('industry', 'i45.w', 114, 'Re-processing of secondary construction material into aggregates', 'A_CONW', 'ISIC_F', 'Construction (F)', 'Construction', 'Construction', null),
  ('industry', 'i50.a', 115, 'Sale, maintenance, repair of motor vehicles, motor vehicles parts, motorcycles, motor cycles parts and accessoiries', 'A_TDMO', 'ISIC_G_H', 'Wholesale retail trade, repair of motor vehicles, motorcycles, etc.; hotels and restaurants (G+H)', 'Trade', 'Wholesale, retail & hospitality', null),
  ('industry', 'i50.b', 116, 'Retail sale of automotive fuel', 'A_TDFU', 'ISIC_G_H', 'Wholesale retail trade, repair of motor vehicles, motorcycles, etc.; hotels and restaurants (G+H)', 'Trade', 'Wholesale, retail & hospitality', null),
  ('industry', 'i51', 117, 'Wholesale trade and commission trade, except of motor vehicles and motorcycles (51)', 'A_TDWH', 'ISIC_G_H', 'Wholesale retail trade, repair of motor vehicles, motorcycles, etc.; hotels and restaurants (G+H)', 'Trade', 'Wholesale, retail & hospitality', null),
  ('industry', 'i52', 118, 'Retail trade, except of motor vehicles and motorcycles; repair of personal and household goods (52)', 'A_TDRT', 'ISIC_G_H', 'Wholesale retail trade, repair of motor vehicles, motorcycles, etc.; hotels and restaurants (G+H)', 'Trade', 'Wholesale, retail & hospitality', null),
  ('industry', 'i55', 119, 'Hotels and restaurants (55)', 'A_HORE', 'ISIC_G_H', 'Wholesale retail trade, repair of motor vehicles, motorcycles, etc.; hotels and restaurants (G+H)', 'Services', 'Wholesale, retail & hospitality', null),
  ('industry', 'i60.1', 120, 'Transport via railways', 'A_TRAI', 'ISIC_I', 'Transport, storage and communications (I)', 'Mobility', 'Transport, storage & communications', null),
  ('industry', 'i60.2', 121, 'Other land transport', 'A_TLND', 'ISIC_I', 'Transport, storage and communications (I)', 'Mobility', 'Transport, storage & communications', null),
  ('industry', 'i60.3', 122, 'Transport via pipelines', 'A_TPIP', 'ISIC_I', 'Transport, storage and communications (I)', 'Mobility', 'Transport, storage & communications', null),
  ('industry', 'i61.1', 123, 'Sea and coastal water transport', 'A_TWAS', 'ISIC_I', 'Transport, storage and communications (I)', 'Mobility', 'Transport, storage & communications', null),
  ('industry', 'i61.2', 124, 'Inland water transport', 'A_TWAI', 'ISIC_I', 'Transport, storage and communications (I)', 'Mobility', 'Transport, storage & communications', null),
  ('industry', 'i62', 125, 'Air transport (62)', 'A_TAIR', 'ISIC_I', 'Transport, storage and communications (I)', 'Mobility', 'Transport, storage & communications', null),
  ('industry', 'i63', 126, 'Supporting and auxiliary transport activities; activities of travel agencies (63)', 'A_TAUX', 'ISIC_I', 'Transport, storage and communications (I)', 'Mobility', 'Transport, storage & communications', null),
  ('industry', 'i64', 127, 'Post and telecommunications (64)', 'A_PTEL', 'ISIC_I', 'Transport, storage and communications (I)', 'Mobility', 'Transport, storage & communications', null),
  ('industry', 'i65', 128, 'Financial intermediation, except insurance and pension funding (65)', 'A_FINT', 'ISIC_J_K', 'Financial intermediation; real estate, renting and business activities (J+K)', 'Services', 'Finance, real estate & business services', null),
  ('industry', 'i66', 129, 'Insurance and pension funding, except compulsory social security (66)', 'A_FINS', 'ISIC_J_K', 'Financial intermediation; real estate, renting and business activities (J+K)', 'Services', 'Finance, real estate & business services', null),
  ('industry', 'i67', 130, 'Activities auxiliary to financial intermediation (67)', 'A_FAUX', 'ISIC_J_K', 'Financial intermediation; real estate, renting and business activities (J+K)', 'Services', 'Finance, real estate & business services', null),
  ('industry', 'i70', 131, 'Real estate activities (70)', 'A_REAL', 'ISIC_J_K', 'Financial intermediation; real estate, renting and business activities (J+K)', 'Services', 'Finance, real estate & business services', null),
  ('industry', 'i71', 132, 'Renting of machinery and equipment without operator and of personal and household goods (71)', 'A_MARE', 'ISIC_J_K', 'Financial intermediation; real estate, renting and business activities (J+K)', 'Services', 'Finance, real estate & business services', null),
  ('industry', 'i72', 133, 'Computer and related activities (72)', 'A_COMP', 'ISIC_J_K', 'Financial intermediation; real estate, renting and business activities (J+K)', 'Services', 'Finance, real estate & business services', null),
  ('industry', 'i73', 134, 'Research and development (73)', 'A_RESD', 'ISIC_J_K', 'Financial intermediation; real estate, renting and business activities (J+K)', 'Services', 'Finance, real estate & business services', null),
  ('industry', 'i74', 135, 'Other business activities (74)', 'A_OBUS', 'ISIC_J_K', 'Financial intermediation; real estate, renting and business activities (J+K)', 'Services', 'Finance, real estate & business services', null),
  ('industry', 'i75', 136, 'Public administration and defence; compulsory social security (75)', 'A_PADF', 'ISIC_L', 'Public administration and defense; compulsory social security (L)', 'Services', 'Public administration & defence', null),
  ('industry', 'i80', 137, 'Education (80)', 'A_EDUC', 'ISIC_M_N_O', 'Education; health and social work; other community, social and personal services (M+N+O)', 'Services', 'Education, health & other services', null),
  ('industry', 'i85', 138, 'Health and social work (85)', 'A_HEAL', 'ISIC_M_N_O', 'Education; health and social work; other community, social and personal services (M+N+O)', 'Services', 'Education, health & other services', null),
  ('industry', 'i90.1.a', 139, 'Incineration of waste: Food', 'A_INCF', 'ISIC_M_N_O', 'Education; health and social work; other community, social and personal services (M+N+O)', 'Shelter', 'Waste, recycling & water treatment', null),
  ('industry', 'i90.1.b', 140, 'Incineration of waste: Paper', 'A_INCP', 'ISIC_M_N_O', 'Education; health and social work; other community, social and personal services (M+N+O)', 'Shelter', 'Waste, recycling & water treatment', null),
  ('industry', 'i90.1.c', 141, 'Incineration of waste: Plastic', 'A_INCL', 'ISIC_M_N_O', 'Education; health and social work; other community, social and personal services (M+N+O)', 'Shelter', 'Waste, recycling & water treatment', null),
  ('industry', 'i90.1.d', 142, 'Incineration of waste: Metals and Inert materials', 'A_INCM', 'ISIC_M_N_O', 'Education; health and social work; other community, social and personal services (M+N+O)', 'Shelter', 'Waste, recycling & water treatment', null),
  ('industry', 'i90.1.e', 143, 'Incineration of waste: Textiles', 'A_INCT', 'ISIC_M_N_O', 'Education; health and social work; other community, social and personal services (M+N+O)', 'Shelter', 'Waste, recycling & water treatment', null),
  ('industry', 'i90.1.f', 144, 'Incineration of waste: Wood', 'A_INCW', 'ISIC_M_N_O', 'Education; health and social work; other community, social and personal services (M+N+O)', 'Shelter', 'Waste, recycling & water treatment', null),
  ('industry', 'i90.1.g', 145, 'Incineration of waste: Oil/Hazardous waste', 'A_INCO', 'ISIC_M_N_O', 'Education; health and social work; other community, social and personal services (M+N+O)', 'Shelter', 'Waste, recycling & water treatment', null),
  ('industry', 'i90.2.a', 146, 'Biogasification of food waste, incl. land application', 'A_BIOF', 'ISIC_M_N_O', 'Education; health and social work; other community, social and personal services (M+N+O)', 'Shelter', 'Waste, recycling & water treatment', null),
  ('industry', 'i90.2.b', 147, 'Biogasification of paper, incl. land application', 'A_BIOP', 'ISIC_M_N_O', 'Education; health and social work; other community, social and personal services (M+N+O)', 'Shelter', 'Waste, recycling & water treatment', null),
  ('industry', 'i90.2.c', 148, 'Biogasification of sewage slugde, incl. land application', 'A_BIOS', 'ISIC_M_N_O', 'Education; health and social work; other community, social and personal services (M+N+O)', 'Shelter', 'Waste, recycling & water treatment', null),
  ('industry', 'i90.3.a', 149, 'Composting of food waste, incl. land application', 'A_COMF', 'ISIC_M_N_O', 'Education; health and social work; other community, social and personal services (M+N+O)', 'Shelter', 'Waste, recycling & water treatment', null),
  ('industry', 'i90.3.b', 150, 'Composting of paper and wood, incl. land application', 'A_COMW', 'ISIC_M_N_O', 'Education; health and social work; other community, social and personal services (M+N+O)', 'Shelter', 'Waste, recycling & water treatment', null),
  ('industry', 'i90.4.a', 151, 'Waste water treatment, food', 'A_WASF', 'ISIC_M_N_O', 'Education; health and social work; other community, social and personal services (M+N+O)', 'Shelter', 'Waste, recycling & water treatment', null),
  ('industry', 'i90.4.b', 152, 'Waste water treatment, other', 'A_WASO', 'ISIC_M_N_O', 'Education; health and social work; other community, social and personal services (M+N+O)', 'Shelter', 'Waste, recycling & water treatment', null),
  ('industry', 'i90.5.a', 153, 'Landfill of waste: Food', 'A_LANF', 'ISIC_M_N_O', 'Education; health and social work; other community, social and personal services (M+N+O)', 'Shelter', 'Waste, recycling & water treatment', null),
  ('industry', 'i90.5.b', 154, 'Landfill of waste: Paper', 'A_LANP', 'ISIC_M_N_O', 'Education; health and social work; other community, social and personal services (M+N+O)', 'Shelter', 'Waste, recycling & water treatment', null),
  ('industry', 'i90.5.c', 155, 'Landfill of waste: Plastic', 'A_LANL', 'ISIC_M_N_O', 'Education; health and social work; other community, social and personal services (M+N+O)', 'Shelter', 'Waste, recycling & water treatment', null),
  ('industry', 'i90.5.d', 156, 'Landfill of waste: Inert/metal/hazardous', 'A_LANI', 'ISIC_M_N_O', 'Education; health and social work; other community, social and personal services (M+N+O)', 'Shelter', 'Waste, recycling & water treatment', null),
  ('industry', 'i90.5.e', 157, 'Landfill of waste: Textiles', 'A_LANT', 'ISIC_M_N_O', 'Education; health and social work; other community, social and personal services (M+N+O)', 'Shelter', 'Waste, recycling & water treatment', null),
  ('industry', 'i90.5.f', 158, 'Landfill of waste: Wood', 'A_LANW', 'ISIC_M_N_O', 'Education; health and social work; other community, social and personal services (M+N+O)', 'Shelter', 'Waste, recycling & water treatment', null),
  ('industry', 'i91', 159, 'Activities of membership organisation n.e.c. (91)', 'A_ORGA', 'ISIC_M_N_O', 'Education; health and social work; other community, social and personal services (M+N+O)', 'Services', 'Education, health & other services', null),
  ('industry', 'i92', 160, 'Recreational, cultural and sporting activities (92)', 'A_RECR', 'ISIC_M_N_O', 'Education; health and social work; other community, social and personal services (M+N+O)', 'Services', 'Education, health & other services', null),
  ('industry', 'i93', 161, 'Other service activities (93)', 'A_OSER', 'ISIC_M_N_O', 'Education; health and social work; other community, social and personal services (M+N+O)', 'Services', 'Education, health & other services', null),
  ('industry', 'i95', 162, 'Private households with employed persons (95)', 'A_PRHH', 'ISIC_P', 'Private households with employed persons (P)', 'Shelter', 'Households as employers', null),
  ('industry', 'i99', 163, 'Extra-territorial organizations and bodies', 'A_EXTO', 'ISIC_L', 'Public administration and defense; compulsory social security (L)', 'Services', 'Public administration & defence', null),
  ('product',  'p01.a', 1, 'Paddy rice', 'C_PARI', null, null, 'Food', null, 'Commodity'),
  ('product',  'p01.b', 2, 'Wheat', 'C_WHEA', null, null, 'Food', null, 'Commodity'),
  ('product',  'p01.c', 3, 'Cereal grains nec', 'C_OCER', null, null, 'Food', null, 'Commodity'),
  ('product',  'p01.d', 4, 'Vegetables, fruit, nuts', 'C_FVEG', null, null, 'Food', null, 'Commodity'),
  ('product',  'p01.e', 5, 'Oil seeds', 'C_OILS', null, null, 'Food', null, 'Commodity'),
  ('product',  'p01.f', 6, 'Sugar cane, sugar beet', 'C_SUGB', null, null, 'Food', null, 'Commodity'),
  ('product',  'p01.g', 7, 'Plant-based fibers', 'C_FIBR', null, null, 'Food', null, 'Commodity'),
  ('product',  'p01.h', 8, 'Crops nec', 'C_OTCR', null, null, 'Food', null, 'Commodity'),
  ('product',  'p01.i', 9, 'Cattle', 'C_CATL', null, null, 'Food', null, 'Commodity'),
  ('product',  'p01.j', 10, 'Pigs', 'C_PIGS', null, null, 'Food', null, 'Commodity'),
  ('product',  'p01.k', 11, 'Poultry', 'C_PLTR', null, null, 'Food', null, 'Commodity'),
  ('product',  'p01.l', 12, 'Meat animals nec', 'C_OMEA', null, null, 'Food', null, 'Commodity'),
  ('product',  'p01.m', 13, 'Animal products nec', 'C_OANP', null, null, 'Food', null, 'Commodity'),
  ('product',  'p01.n', 14, 'Raw milk', 'C_MILK', null, null, 'Food', null, 'Commodity'),
  ('product',  'p01.o', 15, 'Wool, silk-worm cocoons', 'C_WOOL', null, null, 'Clothing', null, 'Commodity'),
  ('product',  'p01.w.1', 16, 'Manure (conventional treatment)', 'C_MANC', null, null, 'Food', null, 'Waste'),
  ('product',  'p01.w.2', 17, 'Manure (biogas treatment)', 'C_MANB', null, null, 'Food', null, 'Waste'),
  ('product',  'p02', 18, 'Products of forestry, logging and related services (02)', 'C_FORE', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p05', 19, 'Fish and other fishing products; services incidental of fishing (05)', 'C_FISH', null, null, 'Food', null, 'Commodity'),
  ('product',  'p10.a', 20, 'Anthracite', 'C_ANTH', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p10.b', 21, 'Coking Coal', 'C_COKC', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p10.c', 22, 'Other Bituminous Coal', 'C_OTBC', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p10.d', 23, 'Sub-Bituminous Coal', 'C_SUBC', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p10.e', 24, 'Patent Fuel', 'C_PATF', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p10.f', 25, 'Lignite/Brown Coal', 'C_LIBC', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p10.g', 26, 'BKB/Peat Briquettes', 'C_BKBP', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p10.h', 27, 'Peat', 'C_PEAT', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p11.a', 28, 'Crude petroleum and services related to crude oil extraction, excluding surveying', 'C_COIL', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p11.b', 29, 'Natural gas and services related to natural gas extraction, excluding surveying', 'C_GASE', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p11.b.1', 30, 'Natural Gas Liquids', 'C_GASL', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p11.c', 31, 'Other Hydrocarbons', 'C_OGPL', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p12', 32, 'Uranium and thorium ores (12)', 'C_ORAN', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p13.1', 33, 'Iron ores', 'C_IRON', null, null, 'Construction', null, 'Commodity'),
  ('product',  'p13.20.11', 34, 'Copper ores and concentrates', 'C_COPO', null, null, 'Construction', null, 'Commodity'),
  ('product',  'p13.20.12', 35, 'Nickel ores and concentrates', 'C_NIKO', null, null, 'Construction', null, 'Commodity'),
  ('product',  'p13.20.13', 36, 'Aluminium ores and concentrates', 'C_ALUO', null, null, 'Construction', null, 'Commodity'),
  ('product',  'p13.20.14', 37, 'Precious metal ores and concentrates', 'C_PREO', null, null, 'Construction', null, 'Commodity'),
  ('product',  'p13.20.15', 38, 'Lead, zinc and tin ores and concentrates', 'C_LZTO', null, null, 'Construction', null, 'Commodity'),
  ('product',  'p13.20.16', 39, 'Other non-ferrous metal ores and concentrates', 'C_ONFO', null, null, 'Construction', null, 'Commodity'),
  ('product',  'p14.1', 40, 'Stone', 'C_STON', null, null, 'Construction', null, 'Commodity'),
  ('product',  'p14.2', 41, 'Sand and clay', 'C_SDCL', null, null, 'Construction', null, 'Commodity'),
  ('product',  'p14.3', 42, 'Chemical and fertilizer minerals, salt and other mining and quarrying products n.e.c.', 'C_CHMF', null, null, 'Food', null, 'Commodity'),
  ('product',  'p15.a', 43, 'Products of meat cattle', 'C_PCAT', null, null, 'Food', null, 'Commodity'),
  ('product',  'p15.b', 44, 'Products of meat pigs', 'C_PPIG', null, null, 'Food', null, 'Commodity'),
  ('product',  'p15.c', 45, 'Products of meat poultry', 'C_PPLT', null, null, 'Food', null, 'Commodity'),
  ('product',  'p15.d', 46, 'Meat products nec', 'C_POME', null, null, 'Food', null, 'Commodity'),
  ('product',  'p15.e', 47, 'products of Vegetable oils and fats', 'C_VOIL', null, null, 'Food', null, 'Commodity'),
  ('product',  'p15.f', 48, 'Dairy products', 'C_DAIR', null, null, 'Food', null, 'Commodity'),
  ('product',  'p15.g', 49, 'Processed rice', 'C_RICE', null, null, 'Food', null, 'Commodity'),
  ('product',  'p15.h', 50, 'Sugar', 'C_SUGR', null, null, 'Food', null, 'Commodity'),
  ('product',  'p15.i', 51, 'Food products nec', 'C_OFOD', null, null, 'Food', null, 'Commodity'),
  ('product',  'p15.j', 52, 'Beverages', 'C_BEVR', null, null, 'Food', null, 'Commodity'),
  ('product',  'p15.k', 53, 'Fish products', 'C_FSHP', null, null, 'Food', null, 'Commodity'),
  ('product',  'p16', 54, 'Tobacco products (16)', 'C_TOBC', null, null, 'Food', null, 'Commodity'),
  ('product',  'p17', 55, 'Textiles (17)', 'C_TEXT', null, null, 'Clothing', null, 'Commodity'),
  ('product',  'p18', 56, 'Wearing apparel; furs (18)', 'C_GARM', null, null, 'Clothing', null, 'Commodity'),
  ('product',  'p19', 57, 'Leather and leather products (19)', 'C_LETH', null, null, 'Clothing', null, 'Commodity'),
  ('product',  'p20', 58, 'Wood and products of wood and cork (except furniture); articles of straw and plaiting materials (20)', 'C_WOOD', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p20.w', 59, 'Wood material for treatment, Re-processing of secondary wood material into new wood material', 'C_WOOW', null, null, 'Shelter', null, 'Waste'),
  ('product',  'p21.1', 60, 'Pulp', 'C_PULP', null, null, 'Manufactured_products', null, 'Commodity'),
  ('product',  'p21.w.1', 61, 'Secondary paper for treatment, Re-processing of secondary paper into new pulp', 'C_PAPR', null, null, 'Manufactured_products', null, 'Waste'),
  ('product',  'p21.2', 62, 'Paper and paper products', 'C_PAPE', null, null, 'Manufactured_products', null, 'Commodity'),
  ('product',  'p22', 63, 'Printed matter and recorded media (22)', 'C_MDIA', null, null, 'Manufactured_products', null, 'Commodity'),
  ('product',  'p23.1.a', 64, 'Coke Oven Coke', 'C_COKE', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p23.1.b', 65, 'Gas Coke', 'C_GCOK', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p23.1.c', 66, 'Coal Tar', 'C_COTA', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p23.20.a', 67, 'Motor Gasoline', 'C_MGSL', null, null, 'Mobility', null, 'Commodity'),
  ('product',  'p23.20.b', 68, 'Aviation Gasoline', 'C_AGSL', null, null, 'Mobility', null, 'Commodity'),
  ('product',  'p23.20.c', 69, 'Gasoline Type Jet Fuel', 'C_GJET', null, null, 'Mobility', null, 'Commodity'),
  ('product',  'p23.20.d', 70, 'Kerosene Type Jet Fuel', 'C_KJET', null, null, 'Mobility', null, 'Commodity'),
  ('product',  'p23.20.e', 71, 'Kerosene', 'C_KERO', null, null, 'Mobility', null, 'Commodity'),
  ('product',  'p23.20.f', 72, 'Gas/Diesel Oil', 'C_DOIL', null, null, 'Mobility', null, 'Commodity'),
  ('product',  'p23.20.g', 73, 'Heavy Fuel Oil', 'C_FOIL', null, null, 'Mobility', null, 'Commodity'),
  ('product',  'p23.20.h', 74, 'Refinery Gas', 'C_RGAS', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p23.20.i', 75, 'Liquefied Petroleum Gases (LPG)', 'C_LPGA', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p23.20.j', 76, 'Refinery Feedstocks', 'C_REFF', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p23.20.k', 77, 'Ethane', 'C_ETHA', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p23.20.l', 78, 'Naphtha', 'C_NAPT', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p23.20.m', 79, 'White Spirit & SBP', 'C_WHSP', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p23.20.n', 80, 'Lubricants', 'C_LUBR', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p23.20.o', 81, 'Bitumen', 'C_BITU', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p23.20.p', 82, 'Paraffin Waxes', 'C_PARW', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p23.20.q', 83, 'Petroleum Coke', 'C_PETC', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p23.20.r', 84, 'Non-specified Petroleum Products', 'C_NSPP', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p23.3', 85, 'Nuclear fuel', 'C_NUCF', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p24.a', 86, 'Plastics, basic', 'C_PLAS', null, null, 'Manufactured_products', null, 'Commodity'),
  ('product',  'p24.a.w', 87, 'Secondary plastic for treatment, Re-processing of secondary plastic into new plastic', 'C_PLAW', null, null, 'Manufactured_products', null, 'Waste'),
  ('product',  'p24.b', 88, 'N-fertiliser', 'C_NFER', null, null, 'Food', null, 'Commodity'),
  ('product',  'p24.c', 89, 'P- and other fertiliser', 'C_PFER', null, null, 'Food', null, 'Commodity'),
  ('product',  'p24.d', 90, 'Chemicals nec', 'C_CHEM', null, null, 'Manufactured_products', null, 'Commodity'),
  ('product',  'p24.e', 91, 'Charcoal', 'C_CHAR', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p24.f', 92, 'Additives/Blending Components', 'C_ADDC', null, null, 'Mobility', null, 'Commodity'),
  ('product',  'p24.g', 93, 'Biogasoline', 'C_BIOG', null, null, 'Mobility', null, 'Commodity'),
  ('product',  'p24.h', 94, 'Biodiesels', 'C_BIOD', null, null, 'Mobility', null, 'Commodity'),
  ('product',  'p24.i', 95, 'Other Liquid Biofuels', 'C_OBIO', null, null, 'Mobility', null, 'Commodity'),
  ('product',  'p25', 96, 'Rubber and plastic products (25)', 'C_RUBP', null, null, 'Manufactured_products', null, 'Commodity'),
  ('product',  'p26.a', 97, 'Glass and glass products', 'C_GLAS', null, null, 'Construction', null, 'Commodity'),
  ('product',  'p26.a.w', 98, 'Secondary glass for treatment, Re-processing of secondary glass into new glass', 'C_GLAW', null, null, 'Construction', null, 'Waste'),
  ('product',  'p26.b', 99, 'Ceramic goods', 'C_CRMC', null, null, 'Construction', null, 'Commodity'),
  ('product',  'p26.c', 100, 'Bricks, tiles and construction products, in baked clay', 'C_BRIK', null, null, 'Construction', null, 'Commodity'),
  ('product',  'p26.d', 101, 'Cement, lime and plaster', 'C_CMNT', null, null, 'Construction', null, 'Commodity'),
  ('product',  'p26.d.w', 102, 'Ash for treatment, Re-processing of ash into clinker', 'C_ASHW', null, null, 'Construction', null, 'Waste'),
  ('product',  'p26.e', 103, 'Other non-metallic mineral products', 'C_ONMM', null, null, 'Construction', null, 'Commodity'),
  ('product',  'p27.a', 104, 'Basic iron and steel and of ferro-alloys and first products thereof', 'C_STEL', null, null, 'Manufactured_products', null, 'Commodity'),
  ('product',  'p27.a.w', 105, 'Secondary steel for treatment, Re-processing of secondary steel into new steel', 'C_STEW', null, null, 'Manufactured_products', null, 'Waste'),
  ('product',  'p27.41', 106, 'Precious metals', 'C_PREM', null, null, 'Manufactured_products', null, 'Commodity'),
  ('product',  'p27.41.w', 107, 'Secondary preciuos metals for treatment, Re-processing of secondary preciuos metals into new preciuos metals', 'C_PREW', null, null, 'Manufactured_products', null, 'Waste'),
  ('product',  'p27.42', 108, 'Aluminium and aluminium products', 'C_ALUM', null, null, 'Manufactured_products', null, 'Commodity'),
  ('product',  'p27.42.w', 109, 'Secondary aluminium for treatment, Re-processing of secondary aluminium into new aluminium', 'C_ALUW', null, null, 'Manufactured_products', null, 'Waste'),
  ('product',  'p27.43', 110, 'Lead, zinc and tin and products thereof', 'C_LZTP', null, null, 'Manufactured_products', null, 'Commodity'),
  ('product',  'p27.43.w', 111, 'Secondary lead for treatment, Re-processing of secondary lead into new lead', 'C_LZTW', null, null, 'Manufactured_products', null, 'Waste'),
  ('product',  'p27.44', 112, 'Copper products', 'C_COPP', null, null, 'Manufactured_products', null, 'Commodity'),
  ('product',  'p27.44.w', 113, 'Secondary copper for treatment, Re-processing of secondary copper into new copper', 'C_COPW', null, null, 'Manufactured_products', null, 'Waste'),
  ('product',  'p27.45', 114, 'Other non-ferrous metal products', 'C_ONFM', null, null, 'Manufactured_products', null, 'Commodity'),
  ('product',  'p27.45.w', 115, 'Secondary other non-ferrous metals for treatment, Re-processing of secondary other non-ferrous metals into new other non-ferrous metals', 'C_ONFW', null, null, 'Manufactured_products', null, 'Waste'),
  ('product',  'p27.5', 116, 'Foundry work services', 'C_METC', null, null, 'Manufactured_products', null, 'Commodity'),
  ('product',  'p28', 117, 'Fabricated metal products, except machinery and equipment (28)', 'C_FABM', null, null, 'Manufactured_products', null, 'Commodity'),
  ('product',  'p29', 118, 'Machinery and equipment n.e.c. (29)', 'C_MACH', null, null, 'Manufactured_products', null, 'Commodity'),
  ('product',  'p30', 119, 'Office machinery and computers (30)', 'C_OFMA', null, null, 'Manufactured_products', null, 'Commodity'),
  ('product',  'p31', 120, 'Electrical machinery and apparatus n.e.c. (31)', 'C_ELMA', null, null, 'Manufactured_products', null, 'Commodity'),
  ('product',  'p32', 121, 'Radio, television and communication equipment and apparatus (32)', 'C_RATV', null, null, 'Manufactured_products', null, 'Commodity'),
  ('product',  'p33', 122, 'Medical, precision and optical instruments, watches and clocks (33)', 'C_MEIN', null, null, 'Manufactured_products', null, 'Commodity'),
  ('product',  'p34', 123, 'Motor vehicles, trailers and semi-trailers (34)', 'C_MOTO', null, null, 'Manufactured_products', null, 'Commodity'),
  ('product',  'p35', 124, 'Other transport equipment (35)', 'C_OTRE', null, null, 'Manufactured_products', null, 'Commodity'),
  ('product',  'p36', 125, 'Furniture; other manufactured goods n.e.c. (36)', 'C_FURN', null, null, 'Manufactured_products', null, 'Commodity'),
  ('product',  'p37', 126, 'Secondary raw materials', 'C_RYMS', null, null, 'Manufactured_products', null, 'Commodity'),
  ('product',  'p37.w.1', 127, 'Bottles for treatment, Recycling of bottles by direct reuse', 'C_BOTW', null, null, 'Manufactured_products', null, 'Waste'),
  ('product',  'p40.11.a', 128, 'Electricity by coal', 'C_POWC', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p40.11.b', 129, 'Electricity by gas', 'C_POWG', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p40.11.c', 130, 'Electricity by nuclear', 'C_POWN', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p40.11.d', 131, 'Electricity by hydro', 'C_POWH', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p40.11.e', 132, 'Electricity by wind', 'C_POWW', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p40.11.f', 133, 'Electricity by petroleum and other oil derivatives', 'C_POWP', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p40.11.g', 134, 'Electricity by biomass and waste', 'C_POWB', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p40.11.h', 135, 'Electricity by solar photovoltaic', 'C_POWS', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p40.11.i', 136, 'Electricity by solar thermal', 'C_POWE', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p40.11.j', 137, 'Electricity by tide, wave, ocean', 'C_POWO', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p40.11.k', 138, 'Electricity by Geothermal', 'C_POWM', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p40.11.l', 139, 'Electricity nec', 'C_POWZ', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p40.12', 140, 'Transmission services of electricity', 'C_POWT', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p40.13', 141, 'Distribution and trade services of electricity', 'C_POWD', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p40.2.a', 142, 'Coke oven gas', 'C_COOG', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p40.2.b', 143, 'Blast Furnace Gas', 'C_MBFG', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p40.2.c', 144, 'Oxygen Steel Furnace Gas', 'C_MOSG', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p40.2.d', 145, 'Gas Works Gas', 'C_MGWG', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p40.2.e', 146, 'Biogas', 'C_MBIO', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p40.2.1', 147, 'Distribution services of gaseous fuels through mains', 'C_GASD', null, null, 'Shelter', null, 'TradeMargin'),
  ('product',  'p40.3', 148, 'Steam and hot water supply services', 'C_HWAT', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p41', 149, 'Collected and purified water, distribution services of water (41)', 'C_WATR', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p45', 150, 'Construction work (45)', 'C_CONS', null, null, 'Construction', null, 'Commodity'),
  ('product',  'p45.w', 151, 'Secondary construction material for treatment, Re-processing of secondary construction material into aggregates', 'C_CONW', null, null, 'Construction', null, 'TransportMargin'),
  ('product',  'p50.a', 152, 'Sale, maintenance, repair of motor vehicles, motor vehicles parts, motorcycles, motor cycles parts and accessoiries', 'C_TDMO', null, null, 'Trade', null, 'TradeMargin'),
  ('product',  'p50.b', 153, 'Retail trade services of motor fuel', 'C_TDFU', null, null, 'Trade', null, 'TradeMargin'),
  ('product',  'p51', 154, 'Wholesale trade and commission trade services, except of motor vehicles and motorcycles (51)', 'C_TDWH', null, null, 'Trade', null, 'TradeMargin'),
  ('product',  'p52', 155, 'Retail  trade services, except of motor vehicles and motorcycles; repair services of personal and household goods (52)', 'C_TDRT', null, null, 'Trade', null, 'TradeMargin'),
  ('product',  'p55', 156, 'Hotel and restaurant services (55)', 'C_HORE', null, null, 'Services', null, 'Commodity'),
  ('product',  'p60.1', 157, 'Railway transportation services', 'C_TRAI', null, null, 'Mobility', null, 'TransportMargin'),
  ('product',  'p60.2', 158, 'Other land transportation services', 'C_TLND', null, null, 'Mobility', null, 'TransportMargin'),
  ('product',  'p60.3', 159, 'Transportation services via pipelines', 'C_TPIP', null, null, 'Mobility', null, 'TransportMargin'),
  ('product',  'p61.1', 160, 'Sea and coastal water transportation services', 'C_TWAS', null, null, 'Mobility', null, 'TransportMargin'),
  ('product',  'p61.2', 161, 'Inland water transportation services', 'C_TWAI', null, null, 'Mobility', null, 'TransportMargin'),
  ('product',  'p62', 162, 'Air transport services (62)', 'C_TAIR', null, null, 'Mobility', null, 'TransportMargin'),
  ('product',  'p63', 163, 'Supporting and auxiliary transport services; travel agency services (63)', 'C_TAUX', null, null, 'Services', null, 'TransportMargin'),
  ('product',  'p64', 164, 'Post and telecommunication services (64)', 'C_PTEL', null, null, 'Services', null, 'Commodity'),
  ('product',  'p65', 165, 'Financial intermediation services, except insurance and pension funding services (65)', 'C_FINT', null, null, 'Services', null, 'Commodity'),
  ('product',  'p66', 166, 'Insurance and pension funding services, except compulsory social security services (66)', 'C_FINS', null, null, 'Services', null, 'Commodity'),
  ('product',  'p67', 167, 'Services auxiliary to financial intermediation (67)', 'C_FAUX', null, null, 'Services', null, 'Commodity'),
  ('product',  'p70', 168, 'Real estate services (70)', 'C_REAL', null, null, 'Services', null, 'Commodity'),
  ('product',  'p71', 169, 'Renting services of machinery and equipment without operator and of personal and household goods (71)', 'C_MARE', null, null, 'Services', null, 'Commodity'),
  ('product',  'p72', 170, 'Computer and related services (72)', 'C_COMP', null, null, 'Services', null, 'Commodity'),
  ('product',  'p73', 171, 'Research and development services (73)', 'C_RESD', null, null, 'Services', null, 'Commodity'),
  ('product',  'p74', 172, 'Other business services (74)', 'C_OBUS', null, null, 'Services', null, 'Commodity'),
  ('product',  'p75', 173, 'Public administration and defence services; compulsory social security services (75)', 'C_PADF', null, null, 'Services', null, 'Commodity'),
  ('product',  'p80', 174, 'Education services (80)', 'C_EDUC', null, null, 'Services', null, 'Commodity'),
  ('product',  'p85', 175, 'Health and social work services (85)', 'C_HEAL', null, null, 'Services', null, 'Commodity'),
  ('product',  'p90.1.a', 176, 'Food waste for treatment: incineration', 'C_INCF', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p90.1.b', 177, 'Paper waste for treatment: incineration', 'C_INCP', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p90.1.c', 178, 'Plastic waste for treatment: incineration', 'C_INCL', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p90.1.d', 179, 'Intert/metal waste for treatment: incineration', 'C_INCM', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p90.1.e', 180, 'Textiles waste for treatment: incineration', 'C_INCT', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p90.1.f', 181, 'Wood waste for treatment: incineration', 'C_INCW', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p90.1.g', 182, 'Oil/hazardous waste for treatment: incineration', 'C_INCO', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p90.2.a', 183, 'Food waste for treatment: biogasification and land application', 'C_BIOF', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p90.2.b', 184, 'Paper waste for treatment: biogasification and land application', 'C_BIOP', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p90.2.c', 185, 'Sewage sludge for treatment: biogasification and land application', 'C_BIOS', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p90.3.a', 186, 'Food waste for treatment: composting and land application', 'C_COMF', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p90.3.b', 187, 'Paper and wood waste for treatment: composting and land application', 'C_COMW', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p90.4.a', 188, 'Food waste for treatment: waste water treatment', 'C_WASF', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p90.4.b', 189, 'Other waste for treatment: waste water treatment', 'C_WASO', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p90.5.a', 190, 'Food waste for treatment: landfill', 'C_LANF', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p90.5.b', 191, 'Paper for treatment: landfill', 'C_LANP', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p90.5.c', 192, 'Plastic waste for treatment: landfill', 'C_LANL', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p90.5.d', 193, 'Inert/metal/hazardous waste for treatment: landfill', 'C_LANI', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p90.5.e', 194, 'Textiles waste for treatment: landfill', 'C_LANT', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p90.5.f', 195, 'Wood waste for treatment: landfill', 'C_LANW', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p91', 196, 'Membership organisation services n.e.c. (91)', 'C_ORGA', null, null, 'Services', null, 'Commodity'),
  ('product',  'p92', 197, 'Recreational, cultural and sporting services (92)', 'C_RECR', null, null, 'Services', null, 'Commodity'),
  ('product',  'p93', 198, 'Other services (93)', 'C_OSER', null, null, 'Services', null, 'Commodity'),
  ('product',  'p95', 199, 'Private households with employed persons (95)', 'C_PRHH', null, null, 'Shelter', null, 'Commodity'),
  ('product',  'p99', 200, 'Extra-territorial organizations and bodies', 'C_EXTO', null, null, 'Services', null, 'Commodity')on conflict (exio_code) do nothing;


-- ═══ 4. GRANTS AND RLS — reference-table shape ═══════════════════════════════════════════════
--
-- Same shape as the cbam_* reference tables (20260717_cbam_reference_grants_rls.sql): world
-- readable, writable by nobody through the API. These are published classification rows, not
-- customer data, and the supply-chain wizard reads them before a session exists. A hand-run
-- CREATE TABLE grants nothing, so this block is mandatory, not tidying.

grant select on public.sector_display_groups to anon, authenticated;
grant select on public.exiobase_sectors      to anon, authenticated;
grant all    on public.sector_display_groups to service_role;
grant all    on public.exiobase_sectors      to service_role;

alter table public.sector_display_groups enable row level security;
alter table public.exiobase_sectors      enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies
                 where schemaname = 'public' and tablename = 'sector_display_groups'
                   and policyname = 'sector_display_groups_read') then
    create policy sector_display_groups_read on public.sector_display_groups
      for select to anon, authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies
                 where schemaname = 'public' and tablename = 'exiobase_sectors'
                   and policyname = 'exiobase_sectors_read') then
    create policy exiobase_sectors_read on public.exiobase_sectors
      for select to anon, authenticated using (true);
  end if;
end $$;

-- No insert/update/delete policy on either table, deliberately. Seeding is done by this migration
-- as the table owner; nothing reached through the API may write a sector row.


-- ═══ 5. TRUNCATE THE TEST DATA ═══════════════════════════════════════════════════════════════
--
-- ⚠️ DESTRUCTIVE AND IRREVERSIBLE. RUN THIS ONLY WHILE THE PRE-LAUNCH TEST ROWS ARE THE ONLY ROWS.
-- Expected at the time of writing: one supply_chain_registers row named TEST, one
-- scope3_inventories row, twelve campaign_suppliers rows. Confirm those counts first:
--
--   select 'supply_chain_registers' t, count(*) from public.supply_chain_registers
--   union all select 'scope3_inventories', count(*) from public.scope3_inventories
--   union all select 'campaign_suppliers', count(*) from public.campaign_suppliers
--   union all select 'supplier_responses', count(*) from public.supplier_responses;
--
-- If any count is larger than expected, STOP: a real customer row exists and the sector strings
-- must be mapped rather than discarded.
--
-- CASCADE is required, not convenience: supplier_responses carries a foreign key to
-- campaign_suppliers, so truncating the parent without it raises. Naming supplier_responses
-- explicitly makes the loss visible in the statement rather than implied by the keyword.

truncate table
  public.supply_chain_registers,
  public.scope3_inventories,
  public.supplier_responses,
  public.campaign_suppliers
cascade;


-- ═══ 6. CONSTRAINTS THAT COULD ONLY BE ADDED ONCE THE TABLES WERE EMPTY ══════════════════════

-- 6a. scope3_inventories.sector -> a real column, so a real foreign key.
--     It held the 13-key internal vocabulary; it now holds an EXIOBASE industry code. The FK is
--     ON DELETE RESTRICT by omission (NO ACTION), which is correct: a classification row must not
--     disappear from under a saved inventory.
alter table public.scope3_inventories
  add constraint scope3_inventories_sector_fkey
  foreign key (sector) references public.exiobase_sectors (exio_code);

-- The FK alone would admit a PRODUCT code in a column that means "the company's own sector".
-- Postgres cannot express "references only rows where factor_type = 'industry'" in a foreign key,
-- so the prefix does it: industry codes begin 'i' and the table's own check keeps that true.
alter table public.scope3_inventories
  add constraint scope3_inventories_sector_is_industry
  check (sector is null or sector like 'i%');


-- ── 6b. THE JSONB PATHS. READ THIS BEFORE LOOKING FOR A CHECK CONSTRAINT. ────────────────────
--
-- ⚠️ A CHECK CONSTRAINT CANNOT DO THIS, AND NOTHING WEAKER IS WORTH ADDING.
-- Postgres forbids subqueries in CHECK, so no CHECK can ask whether a sector inside a jsonb array
-- exists in exiobase_sectors. The three things a CHECK COULD do are all worse than nothing:
--   · a hardcoded IN-list of 163 codes - a second copy of the vocabulary, drifting from the table
--     it duplicates, and the copy nobody would remember to update;
--   · a LIKE 'i%' shape test - admits 'i-made-this-up' and reads as validation;
--   · nothing at all - leaves the paths as free text, which is what they are today.
-- So this is a trigger. It is the same shape as enforce_supply_chain_entitlement() in
-- 20260913_supply_chain_registers.sql: a BEFORE INSERT OR UPDATE function that raises with a
-- custom SQLSTATE the route can match on.
--
-- PT422 is new in this schema, alongside PT402 (payment required) and the PT409/410/412/413/414
-- family. It means: the payload named a sector that is not in the classification.

create or replace function public.assert_sector_codes_exist()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  bad text;
begin
  if tg_table_name = 'supply_chain_registers' then
    -- Every element of the suppliers array must carry a sector that exists and is an industry.
    -- A null or absent sector is rejected too: the CSV import path used to default it silently,
    -- and an absent sector reaching storage is the defect that made this necessary.
    -- ⚠️ coalesce, NOT a bare s.sector. string_agg SKIPS NULLS, so aggregating the raw column
    -- would leave `bad` null when every offending row had a MISSING sector - the exact case this
    -- check exists for - and the trigger would raise nothing at all.
    select string_agg(distinct coalesce(s.sector, '(missing)'), ', ')
      into bad
      from jsonb_to_recordset(new.suppliers) as s(sector text)
     where s.sector is null
        or not exists (select 1 from public.exiobase_sectors e
                        where e.exio_code = s.sector and e.factor_type = 'industry');
    if bad is not null then
      raise exception 'Unknown sector code(s) in suppliers: %', bad using errcode = 'PT422';
    end if;
    return new;
  end if;

  if tg_table_name = 'scope3_inventories' then
    -- Two known paths carry a sector inside cat_data. Both are optional; both must be valid when
    -- present. Listed explicitly rather than scanned, so a new sector-bearing path has to be added
    -- here consciously instead of being silently unvalidated.
    select string_agg(v, ', ')
      into bad
      from (values (new.cat_data #>> '{cat1,supplier_sector}'),
                   (new.cat_data #>> '{cat15,portfolio_sector}')) as t(v)
     where v is not null
       and not exists (select 1 from public.exiobase_sectors e
                        where e.exio_code = v and e.factor_type = 'industry');
    if bad is not null then
      raise exception 'Unknown sector code(s) in cat_data: %', bad using errcode = 'PT422';
    end if;
    return new;
  end if;

  return new;
end $$;

comment on function public.assert_sector_codes_exist() is
  'Validates sector codes held inside jsonb, which no CHECK constraint can do: CHECK forbids '
  'subqueries, so membership in exiobase_sectors is unreachable from one. Covers '
  'supply_chain_registers.suppliers[].sector and scope3_inventories.cat_data cat1.supplier_sector '
  'and cat15.portfolio_sector. Raises SQLSTATE PT422.';

drop trigger if exists trg_supply_chain_registers_sectors on public.supply_chain_registers;
create trigger trg_supply_chain_registers_sectors
  before insert or update on public.supply_chain_registers
  for each row execute function public.assert_sector_codes_exist();

drop trigger if exists trg_scope3_inventories_sectors on public.scope3_inventories;
create trigger trg_scope3_inventories_sectors
  before insert or update on public.scope3_inventories
  for each row execute function public.assert_sector_codes_exist();


-- ═══ 7. KEEPING THE SEED IN STEP WITH THE JSON ═══════════════════════════════════════════════
--
-- The JSON is fingerprinted by lib/emissionFactors/exiobaseSectors.test.ts and that test runs in
-- `npm run build`. This table is not, and cannot be: the build has no database connection, so no
-- vitest assertion can see these rows. The fingerprint is recorded here so the comparison is
-- possible at all, by a human or by a script that connects.

create table if not exists public.reference_data_fingerprints (
  dataset      text primary key,
  fingerprint  text not null,
  source_file  text not null,
  seeded_at    timestamptz not null default now()
);

grant select on public.reference_data_fingerprints to authenticated;
grant all    on public.reference_data_fingerprints to service_role;
alter table public.reference_data_fingerprints enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies
                 where schemaname = 'public' and tablename = 'reference_data_fingerprints'
                   and policyname = 'reference_data_fingerprints_read') then
    create policy reference_data_fingerprints_read on public.reference_data_fingerprints
      for select to authenticated using (true);
  end if;
end $$;

comment on table public.reference_data_fingerprints is
  'What this database was seeded FROM, for reference datasets whose authority is a file in the '
  'repo. The fingerprint is the same sha256 the repo test pins, so a divergence between the file '
  'and the seeded rows is detectable by comparing two strings. Nothing computes this automatically: '
  'the build cannot reach the database. See the note below this table in the migration.';

insert into public.reference_data_fingerprints (dataset, fingerprint, source_file) values
  ('exiobase_sectors',
   'b393d1ad7d4966cd0ddd7c29379c98b362ab9bed01be7e98afd53226647e3341',
   'lib/emissionFactors/exiobaseSectors.json')
on conflict (dataset) do update
  set fingerprint = excluded.fingerprint,
      source_file = excluded.source_file,
      seeded_at   = now();


-- ═══ 8. POST-RUN VERIFICATION — run these and read the output ════════════════════════════════
--
-- select factor_type, count(*) from public.exiobase_sectors group by 1;
--   expect: industry 163, product 200
--
-- select count(*) from public.sector_display_groups;
--   expect: 20
--
-- select g.heading, g.member_count, count(e.exio_code) as actual
--   from public.sector_display_groups g
--   left join public.exiobase_sectors e on e.display_group = g.heading
--  group by 1, 2 having g.member_count <> count(e.exio_code);
--   expect: zero rows. Any row means the seed and the group counts disagree.
--
-- select count(*) from public.exiobase_sectors where factor_type = 'industry' and display_group is null;
--   expect: 0
