-- STEP 3 of 4, READ-ONLY: every stored answer to an option question must now be a value, or a
-- comma-separated list of values. EXPECT NO ROWS. Any row means the backfill left prose behind — read it,
-- then run 9_rollback.sql if you want to put it back before investigating.
-- Generated by scripts/gen-supplier-option-backfill.mjs from lib/supply-chain/templates.ts. Do not edit by hand.
-- 323 label forms across 56 questions (55 radio, 1 checkbox).
-- More forms than options: an option whose wording has changed is listed under every wording it has had.
--
-- ⚠️ THE PATTERN IS THE SHAPE OF A VALUE, not a list of the values themselves: lower case, digits and
--    underscores, optionally comma-separated for a checkbox answer. An off-list answer typed by someone
--    holding a token will show up here too, which is correct — it is not a value either.
select question_id, response, count(*) as rows_left
  from supplier_responses
 where question_id in ('env_policy', 'env_iso14001', 's3cat1_quality', 'env_renewable', 'env_target', 'env_reporting', 'lab_policy', 'lab_iso45001', 'lab_hours', 'lab_wages', 'lab_freedom', 'lab_forced', 'lab_child', 'lab_hrdd', 'eth_anticorruption', 'eth_training', 'eth_incidents', 'eth_whistleblower', 'eth_conflicts', 'eth_gdpr', 'eth_sanctions', 'proc_code', 'proc_assess', 'proc_audit', 'proc_traceability', 'proc_ecovadis', 'proc_scope3cat1', 's3_boundary', 's3_renewable', 's3_target', 's3_assurance', 'ms_policy', 'ms_risk_assess', 'ms_forced', 'ms_recruitment', 'ms_child_policy', 'ms_child_incidents', 'ms_dd_suppliers', 'ms_grievance', 'ms_training', 'ms_statement', 'ms_kpis', 'cs_policy', 'cs_governance', 'cs_scope', 'cs_risk_assess', 'cs_risk_method', 'cs_salient', 'cs_high_risk', 'cs_prevention', 'cs_supplier_code', 'cs_grievance', 'cs_remediation', 'cs_monitoring', 'cs_disclosure', 'cs_stakeholder')
   and response is not null
   and response !~ '^[a-z0-9_]+(, ?[a-z0-9_]+)*$'
 group by 1, 2
 order by 3 desc;
