import { NextRequest, NextResponse } from 'next/server'

const RESEND_API_KEY   = process.env.RESEND_API_KEY!
const FROM_EMAIL       = process.env.RESEND_FROM_EMAIL || 'noreply@themisiq.co'
const MONITOR_EMAIL    = process.env.RESEND_MONITOR_EMAIL!

const DISCLAIMER = `This report is generated by the ThemisIQ platform and is provided for informational and planning purposes only. It does not constitute legal advice, regulatory assurance, or a professional opinion. The accuracy of this output depends on the accuracy of data provided. ThemisIQ Compliance Inc. does not accept responsibility for regulatory filings made on the basis of platform outputs without independent professional review. ThemisIQ is not an accredited assurance provider under any GHG Protocol, CARB, ESRS, or CDP framework.`

const URGENCY_COLOR: Record<string, string> = {
  critical: '#B91C1C', high: '#ba7517', medium: '#0C447C', monitor: '#888784'
}
const URGENCY_BG: Record<string, string> = {
  critical: '#FCEBEB', high: '#FEF3E2', medium: '#E6F1FB', monitor: '#f8f7f5'
}
const URGENCY_TEXT: Record<string, string> = {
  critical: '#501313', high: '#633806', medium: '#0C447C', monitor: '#888784'
}

export async function POST(req: NextRequest) {
  try {
    const { lead, obligations } = await req.json()

    if (!lead?.email || !lead.email.includes('@')) {
      return NextResponse.json({ error: 'Invalid email' }, { status: 400 })
    }

    const total    = obligations.length
    const critical = obligations.filter((o: any) => o.urgency === 'critical').length
    const high     = obligations.filter((o: any) => o.urgency === 'high').length
    const date     = new Date().toLocaleDateString('en-CA', { year: 'numeric', month: 'long', day: 'numeric' })

    // ── BUILD OBLIGATION ROWS ──────────────────────────────────────
    const obligationRows = obligations.map((ob: any, i: number) => `
      <tr style="background:${i % 2 === 0 ? '#fff' : '#f8f7f5'}">
        <td style="padding:10px 14px;border-bottom:1px solid #e8e7e4;font-size:12px;font-weight:600;color:#0d0d0d;vertical-align:top;">
          ${ob.name}
          <div style="font-size:11px;font-weight:400;color:#888784;margin-top:2px;">${ob.jurisdiction}</div>
        </td>
        <td style="padding:10px 14px;border-bottom:1px solid #e8e7e4;vertical-align:top;">
          <span style="font-size:10px;font-weight:700;color:${URGENCY_TEXT[ob.urgency]};background:${URGENCY_BG[ob.urgency]};padding:3px 8px;border-radius:99px;white-space:nowrap;">${ob.urgency_label}</span>
        </td>
        <td style="padding:10px 14px;border-bottom:1px solid #e8e7e4;font-size:12px;color:#555553;vertical-align:top;">${ob.deadline}</td>
        <td style="padding:10px 14px;border-bottom:1px solid #e8e7e4;font-size:12px;color:#7425e3;font-weight:600;vertical-align:top;">${ob.module}</td>
      </tr>`).join('')

    // ── LEAD EMAIL HTML ────────────────────────────────────────────
    const leadHtml = `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Your ThemisIQ Compliance Obligation Map</title></head>
<body style="margin:0;padding:0;background:#f8f7f5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#f8f7f5;">
<tr><td align="center" style="padding:32px 16px;">
<table width="600" cellpadding="0" cellspacing="0" border="0" style="max-width:600px;width:100%;border-radius:12px;overflow:hidden;box-shadow:0 2px 16px rgba(0,0,0,0.08);">

  <!-- GRADIENT TOP -->
  <tr><td style="background:linear-gradient(90deg,#7425e3,#1fb1ff,#64fe3e);height:4px;font-size:1px;line-height:1px;">&nbsp;</td></tr>

  <!-- DARK HEADER -->
  <tr><td style="background:#0d0d0d;padding:24px 32px;">
    <table width="100%" cellpadding="0" cellspacing="0" border="0"><tr>
      <td><span style="font-size:20px;font-weight:800;color:#fff;letter-spacing:-0.5px;">ThemisIQ</span><div style="font-size:11px;color:rgba(255,255,255,0.35);margin-top:2px;">COMPLIANCE INTELLIGENCE</div></td>
      <td align="right"><div style="font-size:11px;font-weight:600;color:rgba(255,255,255,0.4);text-transform:uppercase;letter-spacing:0.07em;">Compliance Obligation Map</div><div style="font-size:11px;color:rgba(255,255,255,0.25);margin-top:2px;">${date}</div></td>
    </tr></table>
  </td></tr>

  <!-- HERO -->
  <tr><td style="background:#111;padding:28px 32px 24px;">
    <div style="font-size:11px;font-weight:600;color:rgba(255,255,255,0.35);letter-spacing:0.08em;text-transform:uppercase;margin-bottom:10px;">Prepared for ${lead.first} ${lead.last} · ${lead.company}</div>
    <div style="font-size:22px;font-weight:400;color:#fff;line-height:1.25;font-family:Georgia,serif;margin-bottom:10px;">We identified <span style="font-style:italic;">${total} regulations</span> that apply to ${lead.company}.</div>
    <div style="font-size:13px;color:rgba(255,255,255,0.5);line-height:1.65;margin-bottom:20px;">${critical} require immediate action. ${high} are high priority. Review your full Compliance Obligation Map below.</div>
    <table cellpadding="0" cellspacing="0" border="0"><tr>
      <td style="padding-right:8px;"><span style="font-size:11px;font-weight:700;color:#B91C1C;background:#FCEBEB;padding:4px 12px;border-radius:99px;">${critical} immediate</span></td>
      <td style="padding-right:8px;"><span style="font-size:11px;font-weight:700;color:#633806;background:#FEF3E2;padding:4px 12px;border-radius:99px;">${high} high priority</span></td>
      <td><span style="font-size:11px;font-weight:700;color:#888784;background:rgba(255,255,255,0.08);padding:4px 12px;border-radius:99px;">${total - critical - high} monitor</span></td>
    </tr></table>
  </td></tr>

  <!-- WHITE BODY -->
  <tr><td style="background:#fff;padding:32px;">
    <div style="font-size:11px;font-weight:600;color:#888784;letter-spacing:0.1em;text-transform:uppercase;margin-bottom:12px;">Your compliance obligations</div>
    <table width="100%" cellpadding="0" cellspacing="0" border="0" style="border:1px solid #e8e7e4;border-radius:8px;overflow:hidden;">
      <tr style="background:#f8f7f5;">
        <th style="padding:8px 14px;text-align:left;font-size:10px;font-weight:600;color:#888784;letter-spacing:0.06em;text-transform:uppercase;border-bottom:1px solid #e8e7e4;">Regulation</th>
        <th style="padding:8px 14px;text-align:left;font-size:10px;font-weight:600;color:#888784;letter-spacing:0.06em;text-transform:uppercase;border-bottom:1px solid #e8e7e4;">Priority</th>
        <th style="padding:8px 14px;text-align:left;font-size:10px;font-weight:600;color:#888784;letter-spacing:0.06em;text-transform:uppercase;border-bottom:1px solid #e8e7e4;">Deadline</th>
        <th style="padding:8px 14px;text-align:left;font-size:10px;font-weight:600;color:#888784;letter-spacing:0.06em;text-transform:uppercase;border-bottom:1px solid #e8e7e4;">Module</th>
      </tr>
      ${obligationRows}
    </table>

    <div style="height:1px;background:linear-gradient(90deg,#7425e3,#1fb1ff,#64fe3e);margin:28px 0;"></div>

    <div style="font-size:11px;font-weight:600;color:#888784;letter-spacing:0.1em;text-transform:uppercase;margin-bottom:16px;">Recommended next steps</div>

    <table cellpadding="0" cellspacing="0" border="0" width="100%" style="margin-bottom:14px;"><tr>
      <td width="32" valign="top" style="padding-right:12px;"><div style="width:28px;height:28px;border-radius:50%;background:#0d0d0d;font-size:12px;font-weight:700;color:#fff;text-align:center;line-height:28px;">1</div></td>
      <td valign="top"><div style="font-size:13px;font-weight:600;color:#0d0d0d;margin-bottom:3px;">Review your full Compliance Obligation Map</div><div style="font-size:12px;color:#555553;line-height:1.6;">Each obligation above has a specific deadline and recommended first action. Start with the ones marked IMMEDIATE ACTION.</div></td>
    </tr></table>

    <table cellpadding="0" cellspacing="0" border="0" width="100%" style="margin-bottom:14px;"><tr>
      <td width="32" valign="top" style="padding-right:12px;"><div style="width:28px;height:28px;border-radius:50%;background:#0d0d0d;font-size:12px;font-weight:700;color:#fff;text-align:center;line-height:28px;">2</div></td>
      <td valign="top"><div style="font-size:13px;font-weight:600;color:#0d0d0d;margin-bottom:3px;">Start your free 14-day trial</div><div style="font-size:12px;color:#555553;line-height:1.6;">ThemisIQ can have your most urgent obligations addressed in days. No credit card required for the trial.</div></td>
    </tr></table>

    <table cellpadding="0" cellspacing="0" border="0" width="100%" style="margin-bottom:24px;"><tr>
      <td width="32" valign="top" style="padding-right:12px;"><div style="width:28px;height:28px;border-radius:50%;background:#0d0d0d;font-size:12px;font-weight:700;color:#fff;text-align:center;line-height:28px;">3</div></td>
      <td valign="top"><div style="font-size:13px;font-weight:600;color:#0d0d0d;margin-bottom:3px;">Book a free 30-minute Advisory consultation</div><div style="font-size:12px;color:#555553;line-height:1.6;">A named ThemisIQ advisor will review your obligations, prioritise by risk and effort, and tell you exactly where to start.</div></td>
    </tr></table>

    <table cellpadding="0" cellspacing="0" border="0" width="100%"><tr>
      <td align="center">
        <table cellpadding="0" cellspacing="0" border="0"><tr>
          <td style="padding-right:10px;"><a href="https://app.themisiq.co/signup" style="display:inline-block;font-size:13px;font-weight:600;color:#0d0d0d;background:linear-gradient(135deg,#7425e3,#1fb1ff,#64fe3e);padding:11px 24px;border-radius:8px;text-decoration:none;">Start free trial — 14 days</a></td>
          <td><a href="https://www.themisiq.co/advisory" style="display:inline-block;font-size:13px;font-weight:500;color:#0d0d0d;background:#fff;border:1px solid #e8e7e4;padding:11px 24px;border-radius:8px;text-decoration:none;">Book free consultation</a></td>
        </tr></table>
      </td>
    </tr></table>
  </td></tr>

  <!-- FOOTER -->
  <tr><td style="background:#0d0d0d;padding:20px 32px;">
    <table width="100%" cellpadding="0" cellspacing="0" border="0"><tr>
      <td><div style="font-size:13px;font-weight:700;color:#fff;margin-bottom:3px;">ThemisIQ</div><div style="font-size:11px;color:rgba(255,255,255,0.3);">Compliance Intelligence for Sustainable Business</div><div style="font-size:11px;color:rgba(255,255,255,0.2);margin-top:4px;">www.themisiq.co · hello@themisiq.co</div></td>
      <td align="right" valign="top"><div style="font-size:11px;color:rgba(255,255,255,0.2);text-align:right;line-height:1.6;">You received this because you completed<br>the ThemisIQ Compliance Assessment.<br><a href="https://www.themisiq.co" style="color:rgba(255,255,255,0.25);">Unsubscribe</a></div></td>
    </tr></table>
  </td></tr>

  <!-- DISCLAIMER -->
  <tr><td style="background:#f8f7f5;padding:16px 32px;">
    <p style="font-size:10px;color:#aaa;line-height:1.6;margin:0;">${DISCLAIMER}</p>
  </td></tr>

  <!-- GRADIENT BOTTOM -->
  <tr><td style="background:linear-gradient(90deg,#7425e3,#1fb1ff,#64fe3e);height:3px;font-size:1px;line-height:1px;">&nbsp;</td></tr>

</table>
</td></tr></table>
</body></html>`

    // ── INTERNAL NOTIFICATION HTML ─────────────────────────────────
    const notifyHtml = `<!DOCTYPE html><html><body style="font-family:sans-serif;background:#f8f7f5;padding:24px;">
<div style="max-width:600px;background:#fff;border-radius:8px;overflow:hidden;border:1px solid #e8e7e4;">
  <div style="background:#0d0d0d;padding:16px 20px;display:flex;justify-content:space-between;">
    <span style="color:#fff;font-weight:700;font-size:14px;">ThemisIQ · New Assessment Lead</span>
    <span style="font-size:12px;color:rgba(255,255,255,0.4);">${date}</span>
  </div>
  <div style="padding:20px;">
    <table width="100%" style="margin-bottom:16px;">
      <tr><td width="140" style="font-size:12px;color:#888;font-weight:600;padding:4px 0;">Name</td><td style="font-size:12px;color:#0d0d0d;font-weight:600;">${lead.first} ${lead.last}</td></tr>
      <tr><td style="font-size:12px;color:#888;font-weight:600;padding:4px 0;">Company</td><td style="font-size:12px;color:#0d0d0d;">${lead.company}</td></tr>
      <tr><td style="font-size:12px;color:#888;font-weight:600;padding:4px 0;">Role</td><td style="font-size:12px;color:#0d0d0d;">${lead.role}</td></tr>
      <tr><td style="font-size:12px;color:#888;font-weight:600;padding:4px 0;">Email</td><td style="font-size:12px;color:#7425e3;">${lead.email}</td></tr>
    </table>
    <div style="background:#FCEBEB;border-radius:6px;padding:10px 14px;margin-bottom:16px;">
      <span style="font-size:13px;font-weight:700;color:#501313;">${total} obligations identified · ${critical} requiring immediate action</span>
    </div>
    <table width="100%" style="border:1px solid #e8e7e4;border-radius:6px;overflow:hidden;">
      <tr style="background:#f8f7f5;">
        <th style="padding:6px 10px;text-align:left;font-size:10px;color:#888;font-weight:600;border-bottom:1px solid #e8e7e4;">Regulation</th>
        <th style="padding:6px 10px;text-align:left;font-size:10px;color:#888;font-weight:600;border-bottom:1px solid #e8e7e4;">Priority</th>
        <th style="padding:6px 10px;text-align:left;font-size:10px;color:#888;font-weight:600;border-bottom:1px solid #e8e7e4;">Deadline</th>
      </tr>
      ${obligations.map((ob: any) => `<tr><td style="padding:6px 10px;border-bottom:1px solid #e8e7e4;font-size:12px;font-weight:600;color:#0d0d0d;">${ob.name.substring(0, 50)}</td><td style="padding:6px 10px;border-bottom:1px solid #e8e7e4;font-size:11px;font-weight:700;color:${URGENCY_COLOR[ob.urgency]};">${ob.urgency_label}</td><td style="padding:6px 10px;border-bottom:1px solid #e8e7e4;font-size:11px;color:#555;">${ob.deadline}</td></tr>`).join('')}
    </table>
  </div>
</div>
</body></html>`

    // ── SEND LEAD EMAIL ────────────────────────────────────────────
    const leadRes = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: { 'Authorization': `Bearer ${RESEND_API_KEY}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        from: `ThemisIQ <${FROM_EMAIL}>`,
        to: [lead.email],
        reply_to: 'hello@themisiq.co',
        subject: `Your ThemisIQ Compliance Obligation Map — ${total} regulations identified for ${lead.company}`,
        html: leadHtml,
        text: `ThemisIQ identified ${total} regulations that apply to ${lead.company}. ${critical} require immediate action. Visit www.themisiq.co to start your free trial.`,
      }),
    })

    const leadData = await leadRes.json()

    // ── SEND INTERNAL NOTIFICATION ─────────────────────────────────
    await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: { 'Authorization': `Bearer ${RESEND_API_KEY}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        from: `ThemisIQ <${FROM_EMAIL}>`,
        to: [MONITOR_EMAIL],
        subject: `🔔 New lead: ${lead.first} ${lead.last} · ${lead.company} · ${critical} critical obligations`,
        html: notifyHtml,
        text: `New lead: ${lead.first} ${lead.last} · ${lead.company} · ${lead.email} · ${total} obligations · ${critical} critical`,
      }),
    })

    return NextResponse.json({ success: true, id: leadData.id })

  } catch (error) {
    console.error('Assessment submit error:', error)
    return NextResponse.json({ error: 'Failed to send email' }, { status: 500 })
  }
}
